/**
 * Request Logger Middleware
 *
 * Wraps pino-http to log every HTTP request/response.
 * Binds the correlation `requestId` (set by requestContext middleware)
 * to every log entry via `genReqId`, ensuring end-to-end traceability
 * across log aggregation.
 *
 * @module middleware/requestLogger
 */

import pinoHttp from 'pino-http'
import logger from '../config/logger.js'

const requestLogger = pinoHttp({
  logger,
  // Re-use the correlation ID generated by requestContext middleware
  // instead of generating a separate pino-http request ID.
  genReqId: (req) => req.requestId,
})

export default requestLogger
