/**
 * Request Logger Middleware
 *
 * Wraps pino-http to log every HTTP request/response.
 * Binds the correlation `requestId` (set by requestContext middleware)
 * to every log entry via `genReqId`, ensuring end-to-end traceability
 * across log aggregation.
 *
 * @module middleware/requestLogger
 */

import pinoHttp from 'pino-http'
import logger from '../config/logger.js'

const REDACTED_HEADER_VALUE = '[REDACTED]'
const SENSITIVE_REQUEST_HEADER_NAMES = new Set([
  'authorization',
  'x-step-up-token',
])

export const sanitizeRequestHeaders = (headers = {}) => Object.fromEntries(
  Object.entries(headers || {}).map(([name, value]) => [
    name,
    SENSITIVE_REQUEST_HEADER_NAMES.has(String(name).toLowerCase())
      ? REDACTED_HEADER_VALUE
      : value,
  ]),
)

export const serializeRequest = (req = {}) => ({
  id: req.id,
  method: req.method,
  url: req.url,
  query: req.query,
  params: req.params,
  headers: sanitizeRequestHeaders(req.headers),
  remoteAddress: req.socket?.remoteAddress,
  remotePort: req.socket?.remotePort,
})

const requestLogger = pinoHttp({
  logger,
  // Re-use the correlation ID generated by requestContext middleware
  // instead of generating a separate pino-http request ID.
  genReqId: (req) => req.requestId,
  serializers: {
    req: serializeRequest,
  },
})

export default requestLogger
