/**
 * Request Logger Middleware
 *
 * Wraps pino-http to log every HTTP request/response.
 * Binds the correlation `requestId` (set by requestContext middleware)
 * to every log entry via `genReqId`, ensuring end-to-end traceability
 * across log aggregation.
 *
 * @module middleware/requestLogger
 */

import pinoHttp from 'pino-http'
import logger from '../config/logger.js'

const REDACTED_HEADER_VALUE = '[REDACTED]'
const SENSITIVE_REQUEST_HEADER_NAMES = new Set([
  'authorization',
  'x-step-up-token',
])

const stripUrlQuery = (value) => typeof value === 'string' ? value.split(/[?#]/, 1)[0] : value
const SAFE_QUERY_KEYS = new Set(['page', 'pageSize', 'limit', 'offset'])
export const sanitizeRequestQuery = (query = {}) => Object.fromEntries(
  Object.entries(query || {}).map(([key, value]) => [key,
    SAFE_QUERY_KEYS.has(key) && /^\d{1,9}$/.test(String(value)) && !Array.isArray(value)
      ? value
      : REDACTED_HEADER_VALUE,
  ]),
)

export const sanitizeRequestHeaders = (headers = {}) => Object.fromEntries(
  Object.entries(headers || {}).map(([name, value]) => [
    name,
    SENSITIVE_REQUEST_HEADER_NAMES.has(String(name).toLowerCase())
      ? REDACTED_HEADER_VALUE
      : ['referer', 'referrer'].includes(String(name).toLowerCase()) ? stripUrlQuery(value) : value,
  ]),
)

export const serializeRequest = (req = {}) => ({
  id: req.id,
  method: req.method,
  url: stripUrlQuery(req.url),
  query: sanitizeRequestQuery(req.query),
  params: req.params,
  headers: sanitizeRequestHeaders(req.headers),
  remoteAddress: req.socket?.remoteAddress,
  remotePort: req.socket?.remotePort,
})

const requestLogger = pinoHttp({
  logger,
  // Re-use the correlation ID generated by requestContext middleware
  // instead of generating a separate pino-http request ID.
  genReqId: (req) => req.requestId,
  serializers: {
    req: serializeRequest,
  },
})

export default requestLogger
