/**
 * Provisioning Service
 *
 * Encapsulates the transactional logic for creating customers and
 * tenants with their required defaults.  This corresponds to
 * BACKEND-SPEC §6 "Provisioning logic".
 *
 * Customer creation (SUPER_ADMIN):
 *   - SINGLE_TENANT → default tenant + initial VMF (VMF 1)
 *   - MULTI_TENANT  → customer only (tenants created separately)
 *
 * Tenant creation (Customer Admin / Service Provider):
 *   - Always sets status=ENABLED
 *   - PER_TENANT_SINGLE → auto-create VMF 1
 *   - PER_TENANT_MULTI  → auto-create VMF 1 (recommended)
 *
 * Audit records are created for every provisioned entity.
 */

import { Customer, Tenant, VMF, AuditLog } from '../models/index.js'
import logger from '../config/logger.js'

/* ------------------------------------------------------------------ */
/*  Audit helper                                                      */
/* ------------------------------------------------------------------ */

const audit = async (actorUserId, action, resourceType, resourceId, scope, diff, req) => {
  try {
    await AuditLog.createLog({
      actorUserId,
      action,
      resourceType,
      resourceId,
      scope,
      diff,
      ip: req?.ip,
      userAgent: req?.get?.('user-agent'),
      requestId: req?.requestId,
    })
  } catch (err) {
    // Audit failures must not block the provisioning flow
    logger.error({ err, action, resourceType, resourceId }, 'provisioning audit log failed')
  }
}

/* ------------------------------------------------------------------ */
/*  createCustomerWithDefaults                                        */
/* ------------------------------------------------------------------ */

/**
 * Create a customer and provision its required defaults.
 *
 * @param {Object} payload
 * @param {string} payload.name
 * @param {string} payload.topology       – SINGLE_TENANT | MULTI_TENANT
 * @param {string} payload.vmfPolicy      – SINGLE | MULTI | PER_TENANT_SINGLE | PER_TENANT_MULTI
 * @param {boolean} [payload.isServiceProvider]
 * @param {string[]} [payload.entitlements]
 * @param {Object} [payload.billing]
 * @param {Object} [payload.trial]
 * @param {string} actorUserId            – The SUPER_ADMIN performing the action
 * @param {import('express').Request} [req] – Express request (for audit context)
 * @returns {Promise<{ customer: Object, tenant?: Object, vmf?: Object }>}
 */
export const createCustomerWithDefaults = async (payload, actorUserId, req) => {
  const result = { customer: null, tenant: null, vmf: null }

  /* ---------- 1. Create customer ---------- */
  const customer = new Customer({
    name: payload.name,
    topology: payload.topology,
    vmfPolicy: payload.vmfPolicy,
    isServiceProvider: payload.isServiceProvider ?? false,
    status: 'ACTIVE',
    entitlements: payload.entitlements || [],
    billing: payload.billing || { planCode: 'DEFAULT', cycle: 'MONTHLY' },
    trial: payload.trial || { isTrial: false },
    createdBy: actorUserId,
  })

  // For SINGLE_TENANT we need the default tenant ID before saving,
  // but the tenant also needs the customer ID. We break the cycle by
  // saving customer first without defaultTenantId validation (set it
  // temporarily to skip Mongoose required-if check), then update.

  if (payload.topology === 'SINGLE_TENANT') {
    // Temporarily bypass the required-if validator by creating tenant first
    // using the customer's _id (auto-generated by Mongoose on `new`).
    const tenant = new Tenant({
      customerId: customer._id,
      name: 'Default Tenant',
      website: 'https://default.tenant',
      status: 'ENABLED',
      isDefault: true,
      // Use the actor as the initial tenant admin
      tenantAdminUserIds: [actorUserId],
    })
    await tenant.save()

    customer.defaultTenantId = tenant._id
    await customer.save()

    result.customer = customer
    result.tenant = tenant

    await audit(actorUserId, 'CUSTOMER_CREATED', 'Customer', customer._id, { customerId: customer._id }, null, req)
    await audit(actorUserId, 'TENANT_CREATED', 'Tenant', tenant._id, { customerId: customer._id, tenantId: tenant._id }, null, req)

    /* ---------- Auto-create VMF 1 ---------- */
    const vmf = new VMF({
      customerId: customer._id,
      tenantId: tenant._id,
      name: 'VMF 1',
      status: 'ACTIVE',
      createdBy: actorUserId,
    })
    await vmf.save()
    result.vmf = vmf

    await audit(actorUserId, 'VMF_CREATED', 'VMF', vmf._id, { customerId: customer._id, tenantId: tenant._id, vmfId: vmf._id }, null, req)

    logger.info(
      { customerId: customer._id, tenantId: tenant._id, vmfId: vmf._id },
      'provisioning — single-tenant customer created with default tenant + VMF 1',
    )
  } else {
    /* ---------- MULTI_TENANT — customer only ---------- */
    // No defaultTenantId needed for multi-tenant
    customer.defaultTenantId = undefined
    await customer.save()
    result.customer = customer

    await audit(actorUserId, 'CUSTOMER_CREATED', 'Customer', customer._id, { customerId: customer._id }, null, req)

    logger.info(
      { customerId: customer._id },
      'provisioning — multi-tenant customer created (no default tenant)',
    )
  }

  return result
}

/* ------------------------------------------------------------------ */
/*  createTenantWithDefaults                                          */
/* ------------------------------------------------------------------ */

/**
 * Create a tenant under an existing customer, optionally auto-creating
 * VMF 1 per the customer's vmfPolicy.
 *
 * @param {Object} payload
 * @param {string} payload.customerId
 * @param {string} payload.name
 * @param {string} payload.website
 * @param {string[]} payload.tenantAdminUserIds
 * @param {Object} customer  – The parent Customer document
 * @param {string} actorUserId
 * @param {import('express').Request} [req]
 * @returns {Promise<{ tenant: Object, vmf?: Object }>}
 */
export const createTenantWithDefaults = async (payload, customer, actorUserId, req) => {
  const result = { tenant: null, vmf: null }

  const tenant = new Tenant({
    customerId: customer._id,
    name: payload.name,
    website: payload.website,
    status: 'ENABLED',
    isDefault: false,
    tenantAdminUserIds: payload.tenantAdminUserIds,
  })
  await tenant.save()
  result.tenant = tenant

  await audit(actorUserId, 'TENANT_CREATED', 'Tenant', tenant._id, { customerId: customer._id, tenantId: tenant._id }, null, req)

  /* ---------- Auto-create VMF if policy requires it ---------- */
  if (['PER_TENANT_SINGLE', 'PER_TENANT_MULTI'].includes(customer.vmfPolicy)) {
    const vmf = new VMF({
      customerId: customer._id,
      tenantId: tenant._id,
      name: 'VMF 1',
      status: 'ACTIVE',
      createdBy: actorUserId,
    })
    await vmf.save()
    result.vmf = vmf

    await audit(actorUserId, 'VMF_CREATED', 'VMF', vmf._id, { customerId: customer._id, tenantId: tenant._id, vmfId: vmf._id }, null, req)
  }

  logger.info(
    { customerId: customer._id, tenantId: tenant._id, vmfId: result.vmf?._id },
    `provisioning — tenant created${result.vmf ? ' with VMF 1' : ''}`,
  )

  return result
}
