import RuntimePathRegistry, {
  RUNTIME_PATH_REGISTRY_CATEGORIES,
  RUNTIME_PATH_REGISTRY_DATA_TYPES,
  RUNTIME_PATH_REGISTRY_OPERATIONS,
  RUNTIME_PATH_REGISTRY_SCOPES,
  RUNTIME_PATH_REGISTRY_SOURCE_TYPES,
  RUNTIME_PATH_REGISTRY_STATUSES,
} from '../models/RuntimePathRegistry.js'

export const runtimePathRegistrySeeds = Object.freeze([
  Object.freeze({
    pathKey: 'vmf.id',
    label: 'VMF Id',
    description: 'Unique identifier of the VMF.',
    status: RUNTIME_PATH_REGISTRY_STATUSES.ACTIVE,
    frameworkKeys: Object.freeze(['VMF']),
    scope: RUNTIME_PATH_REGISTRY_SCOPES.FRAMEWORK_STATE,
    allowedOperations: Object.freeze([RUNTIME_PATH_REGISTRY_OPERATIONS.READ]),
    dataType: RUNTIME_PATH_REGISTRY_DATA_TYPES.STRING,
    category: RUNTIME_PATH_REGISTRY_CATEGORIES.METADATA,
    sourceType: RUNTIME_PATH_REGISTRY_SOURCE_TYPES.RUNTIME_STATE,
    isProtected: true,
    isSystem: true,
    introducedInVersion: '1.0.0',
  }),
  Object.freeze({
    pathKey: 'vmf.frameworkKey',
    label: 'VMF Framework Key',
    description: 'Framework key for the VMF instance.',
    status: RUNTIME_PATH_REGISTRY_STATUSES.ACTIVE,
    frameworkKeys: Object.freeze(['VMF']),
    scope: RUNTIME_PATH_REGISTRY_SCOPES.FRAMEWORK_STATE,
    allowedOperations: Object.freeze([RUNTIME_PATH_REGISTRY_OPERATIONS.READ]),
    dataType: RUNTIME_PATH_REGISTRY_DATA_TYPES.STRING,
    category: RUNTIME_PATH_REGISTRY_CATEGORIES.METADATA,
    sourceType: RUNTIME_PATH_REGISTRY_SOURCE_TYPES.RUNTIME_STATE,
    isProtected: true,
    isSystem: true,
    introducedInVersion: '1.0.0',
  }),
  Object.freeze({
    pathKey: 'vmf.packageId',
    label: 'VMF Package Id',
    description: 'Active framework package id for this VMF instance.',
    status: RUNTIME_PATH_REGISTRY_STATUSES.ACTIVE,
    frameworkKeys: Object.freeze(['VMF']),
    scope: RUNTIME_PATH_REGISTRY_SCOPES.FRAMEWORK_STATE,
    allowedOperations: Object.freeze([RUNTIME_PATH_REGISTRY_OPERATIONS.READ]),
    dataType: RUNTIME_PATH_REGISTRY_DATA_TYPES.STRING,
    category: RUNTIME_PATH_REGISTRY_CATEGORIES.METADATA,
    sourceType: RUNTIME_PATH_REGISTRY_SOURCE_TYPES.RUNTIME_STATE,
    isProtected: true,
    isSystem: true,
    introducedInVersion: '1.0.0',
  }),
  Object.freeze({
    pathKey: 'vmf.status',
    label: 'VMF Status',
    description: 'Lifecycle status for the VMF instance.',
    status: RUNTIME_PATH_REGISTRY_STATUSES.ACTIVE,
    frameworkKeys: Object.freeze(['VMF']),
    scope: RUNTIME_PATH_REGISTRY_SCOPES.FRAMEWORK_STATE,
    allowedOperations: Object.freeze([RUNTIME_PATH_REGISTRY_OPERATIONS.READ]),
    dataType: RUNTIME_PATH_REGISTRY_DATA_TYPES.STRING,
    category: RUNTIME_PATH_REGISTRY_CATEGORIES.LIFECYCLE,
    sourceType: RUNTIME_PATH_REGISTRY_SOURCE_TYPES.RUNTIME_STATE,
    isProtected: true,
    isSystem: true,
    introducedInVersion: '1.0.0',
  }),
  Object.freeze({
    pathKey: 'vmf.sections.icp',
    label: 'VMF ICP Section',
    description: 'Ideal customer profile section content.',
    status: RUNTIME_PATH_REGISTRY_STATUSES.ACTIVE,
    frameworkKeys: Object.freeze(['VMF']),
    scope: RUNTIME_PATH_REGISTRY_SCOPES.FRAMEWORK_STATE,
    allowedOperations: Object.freeze([RUNTIME_PATH_REGISTRY_OPERATIONS.READ, RUNTIME_PATH_REGISTRY_OPERATIONS.BIND]),
    dataType: RUNTIME_PATH_REGISTRY_DATA_TYPES.OBJECT,
    category: RUNTIME_PATH_REGISTRY_CATEGORIES.STATE,
    sourceType: RUNTIME_PATH_REGISTRY_SOURCE_TYPES.RUNTIME_STATE,
    isProtected: false,
    isSystem: true,
    introducedInVersion: '1.0.0',
  }),
  Object.freeze({
    pathKey: 'vmf.sections.valueDrivers',
    label: 'VMF Value Drivers Section',
    description: 'Value drivers section content.',
    status: RUNTIME_PATH_REGISTRY_STATUSES.ACTIVE,
    frameworkKeys: Object.freeze(['VMF']),
    scope: RUNTIME_PATH_REGISTRY_SCOPES.FRAMEWORK_STATE,
    allowedOperations: Object.freeze([RUNTIME_PATH_REGISTRY_OPERATIONS.READ, RUNTIME_PATH_REGISTRY_OPERATIONS.BIND]),
    dataType: RUNTIME_PATH_REGISTRY_DATA_TYPES.OBJECT,
    category: RUNTIME_PATH_REGISTRY_CATEGORIES.STATE,
    sourceType: RUNTIME_PATH_REGISTRY_SOURCE_TYPES.RUNTIME_STATE,
    isProtected: false,
    isSystem: true,
    introducedInVersion: '1.0.0',
  }),
  Object.freeze({
    pathKey: 'vmf.sections.customerProblem',
    label: 'VMF Customer Problem Section',
    description: 'Customer problem section content.',
    status: RUNTIME_PATH_REGISTRY_STATUSES.ACTIVE,
    frameworkKeys: Object.freeze(['VMF']),
    scope: RUNTIME_PATH_REGISTRY_SCOPES.FRAMEWORK_STATE,
    allowedOperations: Object.freeze([RUNTIME_PATH_REGISTRY_OPERATIONS.READ, RUNTIME_PATH_REGISTRY_OPERATIONS.BIND]),
    dataType: RUNTIME_PATH_REGISTRY_DATA_TYPES.OBJECT,
    category: RUNTIME_PATH_REGISTRY_CATEGORIES.STATE,
    sourceType: RUNTIME_PATH_REGISTRY_SOURCE_TYPES.RUNTIME_STATE,
    isProtected: false,
    isSystem: true,
    introducedInVersion: '1.0.0',
  }),
  Object.freeze({
    pathKey: 'vmf.validationStatus',
    label: 'VMF Validation Status (Legacy)',
    description: 'Legacy validation status output for VMF runs.',
    status: RUNTIME_PATH_REGISTRY_STATUSES.ACTIVE,
    frameworkKeys: Object.freeze(['VMF']),
    scope: RUNTIME_PATH_REGISTRY_SCOPES.VALIDATION_RESULT,
    allowedOperations: Object.freeze([
      RUNTIME_PATH_REGISTRY_OPERATIONS.READ,
      RUNTIME_PATH_REGISTRY_OPERATIONS.WRITE,
      RUNTIME_PATH_REGISTRY_OPERATIONS.BIND,
    ]),
    dataType: RUNTIME_PATH_REGISTRY_DATA_TYPES.ENUM,
    category: RUNTIME_PATH_REGISTRY_CATEGORIES.VALIDATION,
    sourceType: RUNTIME_PATH_REGISTRY_SOURCE_TYPES.DERIVED,
    isProtected: false,
    isSystem: true,
    introducedInVersion: '1.0.0',
  }),
  Object.freeze({
    pathKey: 'vmf.metadata.lastValidatedAt',
    label: 'VMF Last Validated At',
    description: 'Timestamp of the most recent validation run.',
    status: RUNTIME_PATH_REGISTRY_STATUSES.ACTIVE,
    frameworkKeys: Object.freeze(['VMF']),
    scope: RUNTIME_PATH_REGISTRY_SCOPES.FRAMEWORK_STATE,
    allowedOperations: Object.freeze([
      RUNTIME_PATH_REGISTRY_OPERATIONS.READ,
      RUNTIME_PATH_REGISTRY_OPERATIONS.WRITE,
      RUNTIME_PATH_REGISTRY_OPERATIONS.BIND,
    ]),
    dataType: RUNTIME_PATH_REGISTRY_DATA_TYPES.STRING,
    category: RUNTIME_PATH_REGISTRY_CATEGORIES.METADATA,
    sourceType: RUNTIME_PATH_REGISTRY_SOURCE_TYPES.DERIVED,
    isProtected: false,
    isSystem: true,
    introducedInVersion: '1.0.0',
  }),
  Object.freeze({
    pathKey: 'vmf.metadata',
    label: 'VMF Metadata',
    description: 'Framework-level metadata for VMF runtime state.',
    status: RUNTIME_PATH_REGISTRY_STATUSES.ACTIVE,
    frameworkKeys: Object.freeze(['VMF']),
    scope: RUNTIME_PATH_REGISTRY_SCOPES.FRAMEWORK_STATE,
    allowedOperations: Object.freeze([RUNTIME_PATH_REGISTRY_OPERATIONS.READ]),
    dataType: RUNTIME_PATH_REGISTRY_DATA_TYPES.OBJECT,
    category: RUNTIME_PATH_REGISTRY_CATEGORIES.METADATA,
    sourceType: RUNTIME_PATH_REGISTRY_SOURCE_TYPES.RUNTIME_STATE,
    isProtected: true,
    isSystem: true,
    introducedInVersion: '1.0.0',
  }),
  Object.freeze({
    pathKey: 'vmf.sections.*',
    label: 'VMF Sections',
    description: 'Readable VMF section content paths for governed skills.',
    status: RUNTIME_PATH_REGISTRY_STATUSES.ACTIVE,
    frameworkKeys: Object.freeze(['VMF']),
    scope: RUNTIME_PATH_REGISTRY_SCOPES.FRAMEWORK_STATE,
    allowedOperations: Object.freeze([RUNTIME_PATH_REGISTRY_OPERATIONS.READ, RUNTIME_PATH_REGISTRY_OPERATIONS.BIND]),
    dataType: RUNTIME_PATH_REGISTRY_DATA_TYPES.OBJECT,
    category: RUNTIME_PATH_REGISTRY_CATEGORIES.STATE,
    sourceType: RUNTIME_PATH_REGISTRY_SOURCE_TYPES.RUNTIME_STATE,
    isProtected: false,
    isSystem: true,
    introducedInVersion: '1.0.0',
  }),
  Object.freeze({
    pathKey: 'vmf.validation.status',
    label: 'VMF Validation Status',
    description: 'Validation status output for VMF runs.',
    status: RUNTIME_PATH_REGISTRY_STATUSES.ACTIVE,
    frameworkKeys: Object.freeze(['VMF']),
    scope: RUNTIME_PATH_REGISTRY_SCOPES.VALIDATION_RESULT,
    allowedOperations: Object.freeze([
      RUNTIME_PATH_REGISTRY_OPERATIONS.READ,
      RUNTIME_PATH_REGISTRY_OPERATIONS.WRITE,
      RUNTIME_PATH_REGISTRY_OPERATIONS.BIND,
    ]),
    dataType: RUNTIME_PATH_REGISTRY_DATA_TYPES.ENUM,
    category: RUNTIME_PATH_REGISTRY_CATEGORIES.VALIDATION,
    sourceType: RUNTIME_PATH_REGISTRY_SOURCE_TYPES.DERIVED,
    isProtected: false,
    isSystem: true,
    introducedInVersion: '1.0.0',
  }),
  Object.freeze({
    pathKey: 'vmf.lifecycle.lockState',
    label: 'VMF Lock State',
    description: 'Indicates whether the VMF is locked/published and therefore immutable.',
    status: RUNTIME_PATH_REGISTRY_STATUSES.ACTIVE,
    frameworkKeys: Object.freeze(['VMF']),
    scope: RUNTIME_PATH_REGISTRY_SCOPES.FRAMEWORK_STATE,
    allowedOperations: Object.freeze([RUNTIME_PATH_REGISTRY_OPERATIONS.READ, RUNTIME_PATH_REGISTRY_OPERATIONS.BIND]),
    dataType: RUNTIME_PATH_REGISTRY_DATA_TYPES.ENUM,
    category: RUNTIME_PATH_REGISTRY_CATEGORIES.LIFECYCLE,
    sourceType: RUNTIME_PATH_REGISTRY_SOURCE_TYPES.RUNTIME_STATE,
    isProtected: true,
    isSystem: true,
    introducedInVersion: '1.0.0',
  }),
  Object.freeze({
    pathKey: 'rld.metadata',
    label: 'RLD Metadata',
    description: 'Framework-level metadata for RLD runtime state.',
    status: RUNTIME_PATH_REGISTRY_STATUSES.ACTIVE,
    frameworkKeys: Object.freeze(['RLD']),
    scope: RUNTIME_PATH_REGISTRY_SCOPES.FRAMEWORK_STATE,
    allowedOperations: Object.freeze([RUNTIME_PATH_REGISTRY_OPERATIONS.READ]),
    dataType: RUNTIME_PATH_REGISTRY_DATA_TYPES.OBJECT,
    category: RUNTIME_PATH_REGISTRY_CATEGORIES.METADATA,
    sourceType: RUNTIME_PATH_REGISTRY_SOURCE_TYPES.RUNTIME_STATE,
    isProtected: true,
    isSystem: true,
    introducedInVersion: '1.0.0',
  }),
  Object.freeze({
    pathKey: 'rld.validation.status',
    label: 'RLD Validation Status',
    description: 'Validation status output for RLD runs.',
    status: RUNTIME_PATH_REGISTRY_STATUSES.ACTIVE,
    frameworkKeys: Object.freeze(['RLD']),
    scope: RUNTIME_PATH_REGISTRY_SCOPES.VALIDATION_RESULT,
    allowedOperations: Object.freeze([
      RUNTIME_PATH_REGISTRY_OPERATIONS.READ,
      RUNTIME_PATH_REGISTRY_OPERATIONS.WRITE,
      RUNTIME_PATH_REGISTRY_OPERATIONS.BIND,
    ]),
    dataType: RUNTIME_PATH_REGISTRY_DATA_TYPES.ENUM,
    category: RUNTIME_PATH_REGISTRY_CATEGORIES.VALIDATION,
    sourceType: RUNTIME_PATH_REGISTRY_SOURCE_TYPES.DERIVED,
    isProtected: false,
    isSystem: true,
    introducedInVersion: '1.0.0',
  }),
  Object.freeze({
    pathKey: 'system.actor.userId',
    label: 'Actor User Id',
    description: 'Super Admin / system actor identifier for the executing request.',
    status: RUNTIME_PATH_REGISTRY_STATUSES.ACTIVE,
    frameworkKeys: Object.freeze(['VMF', 'RLD']),
    scope: RUNTIME_PATH_REGISTRY_SCOPES.SYSTEM_CONTEXT,
    allowedOperations: Object.freeze([RUNTIME_PATH_REGISTRY_OPERATIONS.READ, RUNTIME_PATH_REGISTRY_OPERATIONS.BIND]),
    dataType: RUNTIME_PATH_REGISTRY_DATA_TYPES.STRING,
    category: RUNTIME_PATH_REGISTRY_CATEGORIES.SYSTEM,
    sourceType: RUNTIME_PATH_REGISTRY_SOURCE_TYPES.SYSTEM_GENERATED,
    isProtected: true,
    isSystem: true,
    introducedInVersion: '1.0.0',
  }),
  Object.freeze({
    pathKey: 'runtime.validationResult',
    label: 'Runtime Validation Result',
    description: 'Validation result output for the executing skill or workflow step.',
    status: RUNTIME_PATH_REGISTRY_STATUSES.ACTIVE,
    frameworkKeys: Object.freeze(['VMF', 'RLD']),
    scope: RUNTIME_PATH_REGISTRY_SCOPES.RUNTIME_OUTPUT,
    allowedOperations: Object.freeze([
      RUNTIME_PATH_REGISTRY_OPERATIONS.READ,
      RUNTIME_PATH_REGISTRY_OPERATIONS.WRITE,
      RUNTIME_PATH_REGISTRY_OPERATIONS.BIND,
    ]),
    dataType: RUNTIME_PATH_REGISTRY_DATA_TYPES.OBJECT,
    category: RUNTIME_PATH_REGISTRY_CATEGORIES.VALIDATION,
    sourceType: RUNTIME_PATH_REGISTRY_SOURCE_TYPES.DERIVED,
    isProtected: false,
    isSystem: true,
    introducedInVersion: '1.0.0',
  }),
  Object.freeze({
    pathKey: 'runtime.missingSections',
    label: 'Runtime Missing Sections',
    description: 'List of missing framework sections found during validation.',
    status: RUNTIME_PATH_REGISTRY_STATUSES.ACTIVE,
    frameworkKeys: Object.freeze(['VMF', 'RLD']),
    scope: RUNTIME_PATH_REGISTRY_SCOPES.RUNTIME_OUTPUT,
    allowedOperations: Object.freeze([
      RUNTIME_PATH_REGISTRY_OPERATIONS.READ,
      RUNTIME_PATH_REGISTRY_OPERATIONS.WRITE,
      RUNTIME_PATH_REGISTRY_OPERATIONS.BIND,
    ]),
    dataType: RUNTIME_PATH_REGISTRY_DATA_TYPES.ARRAY,
    category: RUNTIME_PATH_REGISTRY_CATEGORIES.VALIDATION,
    sourceType: RUNTIME_PATH_REGISTRY_SOURCE_TYPES.DERIVED,
    isProtected: false,
    isSystem: true,
    introducedInVersion: '1.0.0',
  }),
  Object.freeze({
    pathKey: 'runtime.executionTrace',
    label: 'Runtime Execution Trace',
    description: 'Execution trace for the current run.',
    status: RUNTIME_PATH_REGISTRY_STATUSES.ACTIVE,
    frameworkKeys: Object.freeze(['VMF', 'RLD']),
    scope: RUNTIME_PATH_REGISTRY_SCOPES.RUNTIME_OUTPUT,
    allowedOperations: Object.freeze([
      RUNTIME_PATH_REGISTRY_OPERATIONS.READ,
      RUNTIME_PATH_REGISTRY_OPERATIONS.WRITE,
      RUNTIME_PATH_REGISTRY_OPERATIONS.BIND,
    ]),
    dataType: RUNTIME_PATH_REGISTRY_DATA_TYPES.ARRAY,
    category: RUNTIME_PATH_REGISTRY_CATEGORIES.OUTPUT,
    sourceType: RUNTIME_PATH_REGISTRY_SOURCE_TYPES.DERIVED,
    isProtected: false,
    isSystem: true,
    introducedInVersion: '1.0.0',
  }),
  Object.freeze({
    pathKey: 'runtime.recommendations',
    label: 'Runtime Recommendations',
    description: 'Recommendations produced during execution.',
    status: RUNTIME_PATH_REGISTRY_STATUSES.ACTIVE,
    frameworkKeys: Object.freeze(['VMF', 'RLD']),
    scope: RUNTIME_PATH_REGISTRY_SCOPES.RUNTIME_OUTPUT,
    allowedOperations: Object.freeze([
      RUNTIME_PATH_REGISTRY_OPERATIONS.READ,
      RUNTIME_PATH_REGISTRY_OPERATIONS.WRITE,
      RUNTIME_PATH_REGISTRY_OPERATIONS.BIND,
    ]),
    dataType: RUNTIME_PATH_REGISTRY_DATA_TYPES.ARRAY,
    category: RUNTIME_PATH_REGISTRY_CATEGORIES.OUTPUT,
    sourceType: RUNTIME_PATH_REGISTRY_SOURCE_TYPES.DERIVED,
    isProtected: false,
    isSystem: true,
    introducedInVersion: '1.0.0',
  }),
  Object.freeze({
    pathKey: 'runtime.stepOutputs',
    label: 'Runtime Step Outputs',
    description: 'Outputs collected for each execution step.',
    status: RUNTIME_PATH_REGISTRY_STATUSES.ACTIVE,
    frameworkKeys: Object.freeze(['VMF', 'RLD']),
    scope: RUNTIME_PATH_REGISTRY_SCOPES.RUNTIME_OUTPUT,
    allowedOperations: Object.freeze([
      RUNTIME_PATH_REGISTRY_OPERATIONS.READ,
      RUNTIME_PATH_REGISTRY_OPERATIONS.WRITE,
      RUNTIME_PATH_REGISTRY_OPERATIONS.BIND,
    ]),
    dataType: RUNTIME_PATH_REGISTRY_DATA_TYPES.OBJECT,
    category: RUNTIME_PATH_REGISTRY_CATEGORIES.OUTPUT,
    sourceType: RUNTIME_PATH_REGISTRY_SOURCE_TYPES.DERIVED,
    isProtected: false,
    isSystem: true,
    introducedInVersion: '1.0.0',
  }),
  Object.freeze({
    pathKey: 'artifacts.summary',
    label: 'Artifacts Summary',
    description: 'Generated summary artifact.',
    status: RUNTIME_PATH_REGISTRY_STATUSES.ACTIVE,
    frameworkKeys: Object.freeze(['VMF', 'RLD']),
    scope: RUNTIME_PATH_REGISTRY_SCOPES.SNAPSHOT,
    allowedOperations: Object.freeze([
      RUNTIME_PATH_REGISTRY_OPERATIONS.READ,
      RUNTIME_PATH_REGISTRY_OPERATIONS.WRITE,
      RUNTIME_PATH_REGISTRY_OPERATIONS.BIND,
    ]),
    dataType: RUNTIME_PATH_REGISTRY_DATA_TYPES.STRING,
    category: RUNTIME_PATH_REGISTRY_CATEGORIES.OUTPUT,
    sourceType: RUNTIME_PATH_REGISTRY_SOURCE_TYPES.DERIVED,
    isProtected: false,
    isSystem: true,
    introducedInVersion: '1.0.0',
  }),
  Object.freeze({
    pathKey: 'artifacts.validationReport',
    label: 'Artifacts Validation Report',
    description: 'Generated validation report artifact.',
    status: RUNTIME_PATH_REGISTRY_STATUSES.ACTIVE,
    frameworkKeys: Object.freeze(['VMF', 'RLD']),
    scope: RUNTIME_PATH_REGISTRY_SCOPES.SNAPSHOT,
    allowedOperations: Object.freeze([
      RUNTIME_PATH_REGISTRY_OPERATIONS.READ,
      RUNTIME_PATH_REGISTRY_OPERATIONS.WRITE,
      RUNTIME_PATH_REGISTRY_OPERATIONS.BIND,
    ]),
    dataType: RUNTIME_PATH_REGISTRY_DATA_TYPES.OBJECT,
    category: RUNTIME_PATH_REGISTRY_CATEGORIES.OUTPUT,
    sourceType: RUNTIME_PATH_REGISTRY_SOURCE_TYPES.DERIVED,
    isProtected: false,
    isSystem: true,
    introducedInVersion: '1.0.0',
  }),
  Object.freeze({
    pathKey: 'artifacts.execBrief',
    label: 'Artifacts Exec Brief',
    description: 'Generated execution brief artifact.',
    status: RUNTIME_PATH_REGISTRY_STATUSES.ACTIVE,
    frameworkKeys: Object.freeze(['VMF', 'RLD']),
    scope: RUNTIME_PATH_REGISTRY_SCOPES.SNAPSHOT,
    allowedOperations: Object.freeze([
      RUNTIME_PATH_REGISTRY_OPERATIONS.READ,
      RUNTIME_PATH_REGISTRY_OPERATIONS.WRITE,
      RUNTIME_PATH_REGISTRY_OPERATIONS.BIND,
    ]),
    dataType: RUNTIME_PATH_REGISTRY_DATA_TYPES.OBJECT,
    category: RUNTIME_PATH_REGISTRY_CATEGORIES.OUTPUT,
    sourceType: RUNTIME_PATH_REGISTRY_SOURCE_TYPES.DERIVED,
    isProtected: false,
    isSystem: true,
    introducedInVersion: '1.0.0',
  }),
  Object.freeze({
    pathKey: 'context.currentAction',
    label: 'Context Current Action',
    description: 'Current action being performed in the workflow.',
    status: RUNTIME_PATH_REGISTRY_STATUSES.ACTIVE,
    frameworkKeys: Object.freeze(['VMF', 'RLD']),
    scope: RUNTIME_PATH_REGISTRY_SCOPES.SYSTEM_CONTEXT,
    allowedOperations: Object.freeze([RUNTIME_PATH_REGISTRY_OPERATIONS.READ, RUNTIME_PATH_REGISTRY_OPERATIONS.BIND]),
    dataType: RUNTIME_PATH_REGISTRY_DATA_TYPES.STRING,
    category: RUNTIME_PATH_REGISTRY_CATEGORIES.SYSTEM,
    sourceType: RUNTIME_PATH_REGISTRY_SOURCE_TYPES.SYSTEM_GENERATED,
    isProtected: false,
    isSystem: true,
    introducedInVersion: '1.0.0',
  }),
  Object.freeze({
    pathKey: 'context.currentStep',
    label: 'Context Current Step',
    description: 'Current step key within the workflow execution.',
    status: RUNTIME_PATH_REGISTRY_STATUSES.ACTIVE,
    frameworkKeys: Object.freeze(['VMF', 'RLD']),
    scope: RUNTIME_PATH_REGISTRY_SCOPES.SYSTEM_CONTEXT,
    allowedOperations: Object.freeze([RUNTIME_PATH_REGISTRY_OPERATIONS.READ, RUNTIME_PATH_REGISTRY_OPERATIONS.BIND]),
    dataType: RUNTIME_PATH_REGISTRY_DATA_TYPES.STRING,
    category: RUNTIME_PATH_REGISTRY_CATEGORIES.SYSTEM,
    sourceType: RUNTIME_PATH_REGISTRY_SOURCE_TYPES.SYSTEM_GENERATED,
    isProtected: false,
    isSystem: true,
    introducedInVersion: '1.0.0',
  }),
  Object.freeze({
    pathKey: 'context.userIntent',
    label: 'Context User Intent',
    description: 'Derived user intent for the current session.',
    status: RUNTIME_PATH_REGISTRY_STATUSES.ACTIVE,
    frameworkKeys: Object.freeze(['VMF', 'RLD']),
    scope: RUNTIME_PATH_REGISTRY_SCOPES.SYSTEM_CONTEXT,
    allowedOperations: Object.freeze([RUNTIME_PATH_REGISTRY_OPERATIONS.READ, RUNTIME_PATH_REGISTRY_OPERATIONS.BIND]),
    dataType: RUNTIME_PATH_REGISTRY_DATA_TYPES.STRING,
    category: RUNTIME_PATH_REGISTRY_CATEGORIES.SYSTEM,
    sourceType: RUNTIME_PATH_REGISTRY_SOURCE_TYPES.SYSTEM_GENERATED,
    isProtected: false,
    isSystem: true,
    introducedInVersion: '1.0.0',
  }),
  Object.freeze({
    pathKey: 'package.key',
    label: 'Package Key',
    description: 'Package key for the executing runtime package.',
    status: RUNTIME_PATH_REGISTRY_STATUSES.ACTIVE,
    frameworkKeys: Object.freeze(['VMF', 'RLD']),
    scope: RUNTIME_PATH_REGISTRY_SCOPES.SYSTEM_CONTEXT,
    allowedOperations: Object.freeze([RUNTIME_PATH_REGISTRY_OPERATIONS.READ, RUNTIME_PATH_REGISTRY_OPERATIONS.BIND]),
    dataType: RUNTIME_PATH_REGISTRY_DATA_TYPES.STRING,
    category: RUNTIME_PATH_REGISTRY_CATEGORIES.METADATA,
    sourceType: RUNTIME_PATH_REGISTRY_SOURCE_TYPES.SYSTEM_GENERATED,
    isProtected: true,
    isSystem: true,
    introducedInVersion: '1.0.0',
  }),
  Object.freeze({
    pathKey: 'package.version',
    label: 'Package Version',
    description: 'Package version for the executing runtime package.',
    status: RUNTIME_PATH_REGISTRY_STATUSES.ACTIVE,
    frameworkKeys: Object.freeze(['VMF', 'RLD']),
    scope: RUNTIME_PATH_REGISTRY_SCOPES.SYSTEM_CONTEXT,
    allowedOperations: Object.freeze([RUNTIME_PATH_REGISTRY_OPERATIONS.READ, RUNTIME_PATH_REGISTRY_OPERATIONS.BIND]),
    dataType: RUNTIME_PATH_REGISTRY_DATA_TYPES.STRING,
    category: RUNTIME_PATH_REGISTRY_CATEGORIES.METADATA,
    sourceType: RUNTIME_PATH_REGISTRY_SOURCE_TYPES.SYSTEM_GENERATED,
    isProtected: true,
    isSystem: true,
    introducedInVersion: '1.0.0',
  }),
  Object.freeze({
    pathKey: 'policy.workflowKey',
    label: 'Policy Workflow Key',
    description: 'Workflow key governing the current execution.',
    status: RUNTIME_PATH_REGISTRY_STATUSES.ACTIVE,
    frameworkKeys: Object.freeze(['VMF', 'RLD']),
    scope: RUNTIME_PATH_REGISTRY_SCOPES.SYSTEM_CONTEXT,
    allowedOperations: Object.freeze([RUNTIME_PATH_REGISTRY_OPERATIONS.READ, RUNTIME_PATH_REGISTRY_OPERATIONS.BIND]),
    dataType: RUNTIME_PATH_REGISTRY_DATA_TYPES.STRING,
    category: RUNTIME_PATH_REGISTRY_CATEGORIES.SYSTEM,
    sourceType: RUNTIME_PATH_REGISTRY_SOURCE_TYPES.SYSTEM_GENERATED,
    isProtected: true,
    isSystem: true,
    introducedInVersion: '1.0.0',
  }),
  Object.freeze({
    pathKey: 'policy.currentStage',
    label: 'Policy Current Stage',
    description: 'Current policy stage for the executing workflow.',
    status: RUNTIME_PATH_REGISTRY_STATUSES.ACTIVE,
    frameworkKeys: Object.freeze(['VMF', 'RLD']),
    scope: RUNTIME_PATH_REGISTRY_SCOPES.SYSTEM_CONTEXT,
    allowedOperations: Object.freeze([RUNTIME_PATH_REGISTRY_OPERATIONS.READ, RUNTIME_PATH_REGISTRY_OPERATIONS.BIND]),
    dataType: RUNTIME_PATH_REGISTRY_DATA_TYPES.STRING,
    category: RUNTIME_PATH_REGISTRY_CATEGORIES.SYSTEM,
    sourceType: RUNTIME_PATH_REGISTRY_SOURCE_TYPES.SYSTEM_GENERATED,
    isProtected: false,
    isSystem: true,
    introducedInVersion: '1.0.0',
  }),
  Object.freeze({
    pathKey: 'agent.key',
    label: 'Agent Key',
    description: 'Stable key for the executing agent.',
    status: RUNTIME_PATH_REGISTRY_STATUSES.ACTIVE,
    frameworkKeys: Object.freeze(['VMF', 'RLD']),
    scope: RUNTIME_PATH_REGISTRY_SCOPES.SYSTEM_CONTEXT,
    allowedOperations: Object.freeze([RUNTIME_PATH_REGISTRY_OPERATIONS.READ, RUNTIME_PATH_REGISTRY_OPERATIONS.BIND]),
    dataType: RUNTIME_PATH_REGISTRY_DATA_TYPES.STRING,
    category: RUNTIME_PATH_REGISTRY_CATEGORIES.SYSTEM,
    sourceType: RUNTIME_PATH_REGISTRY_SOURCE_TYPES.SYSTEM_GENERATED,
    isProtected: true,
    isSystem: true,
    introducedInVersion: '1.0.0',
  }),
  Object.freeze({
    pathKey: 'agent.executionPlan',
    label: 'Agent Execution Plan',
    description: 'Agent execution plan for the current run.',
    status: RUNTIME_PATH_REGISTRY_STATUSES.ACTIVE,
    frameworkKeys: Object.freeze(['VMF', 'RLD']),
    scope: RUNTIME_PATH_REGISTRY_SCOPES.SYSTEM_CONTEXT,
    allowedOperations: Object.freeze([RUNTIME_PATH_REGISTRY_OPERATIONS.READ, RUNTIME_PATH_REGISTRY_OPERATIONS.BIND]),
    dataType: RUNTIME_PATH_REGISTRY_DATA_TYPES.OBJECT,
    category: RUNTIME_PATH_REGISTRY_CATEGORIES.SYSTEM,
    sourceType: RUNTIME_PATH_REGISTRY_SOURCE_TYPES.SYSTEM_GENERATED,
    isProtected: true,
    isSystem: true,
    introducedInVersion: '1.0.0',
  }),
])

export const seedRuntimePathRegistry = async ({ actorUserId } = {}) => {
  if (!actorUserId) {
    throw new Error('seedRuntimePathRegistry requires actorUserId')
  }

  const seeded = []

  for (const seedEntry of runtimePathRegistrySeeds) {
    const existing = await RuntimePathRegistry.findOne({ pathKey: seedEntry.pathKey })

    if (existing) {
      console.log(`  [seed] Runtime path already exists: ${seedEntry.pathKey}`)
      seeded.push(existing)
      continue
    }

    const created = await RuntimePathRegistry.create({
      ...seedEntry,
      createdBy: actorUserId,
      updatedBy: actorUserId,
    })

    console.log(`  [seed] Created runtime path: ${created.pathKey}`)
    seeded.push(created)
  }

  return seeded
}
