import {
  VALIDATION_REGISTRY_CATEGORIES,
  VALIDATION_REGISTRY_RESULT_TYPES,
  VALIDATION_REGISTRY_SEVERITIES,
  VALIDATION_REGISTRY_STATUSES,
} from '../models/ValidationRegistry.js'

export const VALIDATION_REGISTRY_SEED_STAGES = Object.freeze({
  MVP: 'mvp',
  VMF_V2_3_1: 'vmf-v2-3-1',
})

const VMF_V2_3_1_SEEDS = Object.freeze([
  Object.freeze({
    key: 'required-sections-check',
    label: 'Required Sections Check',
    description: 'Required Sections Check validation definition for VMF v2.3.1.',
    status: VALIDATION_REGISTRY_STATUSES.ACTIVE,
    supportedFrameworkKeys: Object.freeze(['VMF']),
    category: VALIDATION_REGISTRY_CATEGORIES.COMPLETENESS,
    severity: VALIDATION_REGISTRY_SEVERITIES.ERROR,
    producerSkillId: 'skill-vmf-required-sections-validator',
    defaultAgentIds: Object.freeze(['agent-vmf-submit-validator-agent']),
    outputPath: 'framework_state.validation.required_sections',
    resultType: VALIDATION_REGISTRY_RESULT_TYPES.OBJECT,
    passFieldPath: 'framework_state.validation.required_sections.is_valid',
    detailsFieldPath: 'framework_state.validation.required_sections.missing_sections',
    policyUsable: true,
    packageUsable: true,
    requiresLatestRun: true,
    freshnessDefaultMinutes: 30,
    blockingDefault: true,
    warningOnlyDefault: false,
  }),
  Object.freeze({
    key: 'submit-readiness-check',
    label: 'Submit Readiness Check',
    description: 'Submit Readiness Check validation definition for VMF v2.3.1.',
    status: VALIDATION_REGISTRY_STATUSES.ACTIVE,
    supportedFrameworkKeys: Object.freeze(['VMF']),
    category: VALIDATION_REGISTRY_CATEGORIES.GOVERNANCE,
    severity: VALIDATION_REGISTRY_SEVERITIES.ERROR,
    producerSkillId: 'skill-vmf-submit-readiness-validator',
    defaultAgentIds: Object.freeze(['agent-vmf-submit-validator-agent']),
    outputPath: 'framework_state.validation.submit_readiness',
    resultType: VALIDATION_REGISTRY_RESULT_TYPES.OBJECT,
    passFieldPath: 'framework_state.validation.submit_readiness.is_valid',
    detailsFieldPath: 'framework_state.validation.submit_readiness.message',
    policyUsable: true,
    packageUsable: true,
    requiresLatestRun: true,
    freshnessDefaultMinutes: 30,
    blockingDefault: true,
    warningOnlyDefault: false,
  }),
  Object.freeze({
    key: 'publish-readiness-check',
    label: 'Publish Readiness Check',
    description: 'Publish Readiness Check validation definition for VMF v2.3.1.',
    status: VALIDATION_REGISTRY_STATUSES.ACTIVE,
    supportedFrameworkKeys: Object.freeze(['VMF']),
    category: VALIDATION_REGISTRY_CATEGORIES.GOVERNANCE,
    severity: VALIDATION_REGISTRY_SEVERITIES.ERROR,
    producerSkillId: 'skill-vmf-publish-readiness-validator',
    defaultAgentIds: Object.freeze(['agent-vmf-publish-validator-agent']),
    outputPath: 'framework_state.validation.publish_readiness',
    resultType: VALIDATION_REGISTRY_RESULT_TYPES.OBJECT,
    passFieldPath: 'framework_state.validation.publish_readiness.is_valid',
    detailsFieldPath: 'framework_state.validation.publish_readiness.message',
    policyUsable: true,
    packageUsable: true,
    requiresLatestRun: true,
    freshnessDefaultMinutes: 30,
    blockingDefault: true,
    warningOnlyDefault: false,
  }),
  Object.freeze({
    key: 'proof-points-check',
    label: 'Proof Points Check',
    description: 'Proof Points Check validation definition for VMF v2.3.1.',
    status: VALIDATION_REGISTRY_STATUSES.ACTIVE,
    supportedFrameworkKeys: Object.freeze(['VMF']),
    category: VALIDATION_REGISTRY_CATEGORIES.QUALITY,
    severity: VALIDATION_REGISTRY_SEVERITIES.ERROR,
    producerSkillId: 'skill-vmf-proof-points-validator',
    defaultAgentIds: Object.freeze(['agent-vmf-quality-validator-agent']),
    outputPath: 'framework_state.validation.proof_points',
    resultType: VALIDATION_REGISTRY_RESULT_TYPES.OBJECT,
    passFieldPath: 'framework_state.validation.proof_points.is_valid',
    detailsFieldPath: 'framework_state.validation.proof_points.message',
    policyUsable: true,
    packageUsable: true,
    requiresLatestRun: true,
    freshnessDefaultMinutes: 60,
    blockingDefault: true,
    warningOnlyDefault: false,
  }),
  Object.freeze({
    key: 'metrics-quality-check',
    label: 'Metrics Quality Check',
    description: 'Metrics Quality Check validation definition for VMF v2.3.1.',
    status: VALIDATION_REGISTRY_STATUSES.ACTIVE,
    supportedFrameworkKeys: Object.freeze(['VMF']),
    category: VALIDATION_REGISTRY_CATEGORIES.QUALITY,
    severity: VALIDATION_REGISTRY_SEVERITIES.ERROR,
    producerSkillId: 'skill-vmf-value-metrics-validator',
    defaultAgentIds: Object.freeze(['agent-vmf-quality-validator-agent']),
    outputPath: 'framework_state.validation.metrics_quality',
    resultType: VALIDATION_REGISTRY_RESULT_TYPES.OBJECT,
    passFieldPath: 'framework_state.validation.metrics_quality.is_valid',
    detailsFieldPath: 'framework_state.validation.metrics_quality.message',
    policyUsable: true,
    packageUsable: true,
    requiresLatestRun: true,
    freshnessDefaultMinutes: 60,
    blockingDefault: true,
    warningOnlyDefault: false,
  }),
  Object.freeze({
    key: 'tone-consistency-check',
    label: 'Tone Consistency Check',
    description: 'Tone Consistency Check validation definition for VMF v2.3.1.',
    status: VALIDATION_REGISTRY_STATUSES.ACTIVE,
    supportedFrameworkKeys: Object.freeze(['VMF']),
    category: VALIDATION_REGISTRY_CATEGORIES.QUALITY,
    severity: VALIDATION_REGISTRY_SEVERITIES.WARNING,
    producerSkillId: 'skill-vmf-tone-consistency-validator',
    defaultAgentIds: Object.freeze(['agent-vmf-quality-validator-agent']),
    outputPath: 'framework_state.validation.tone_consistency',
    resultType: VALIDATION_REGISTRY_RESULT_TYPES.OBJECT,
    passFieldPath: 'framework_state.validation.tone_consistency.is_valid',
    detailsFieldPath: 'framework_state.validation.tone_consistency.message',
    policyUsable: true,
    packageUsable: true,
    requiresLatestRun: false,
    freshnessDefaultMinutes: 1440,
    blockingDefault: false,
    warningOnlyDefault: true,
  }),
  Object.freeze({
    key: 'duplicate-content-check',
    label: 'Duplicate Content Check',
    description: 'Duplicate Content Check validation definition for VMF v2.3.1.',
    status: VALIDATION_REGISTRY_STATUSES.ACTIVE,
    supportedFrameworkKeys: Object.freeze(['VMF']),
    category: VALIDATION_REGISTRY_CATEGORIES.CONSISTENCY,
    severity: VALIDATION_REGISTRY_SEVERITIES.WARNING,
    producerSkillId: 'skill-vmf-duplicate-content-validator',
    defaultAgentIds: Object.freeze(['agent-vmf-quality-validator-agent']),
    outputPath: 'framework_state.validation.duplicate_content',
    resultType: VALIDATION_REGISTRY_RESULT_TYPES.OBJECT,
    passFieldPath: 'framework_state.validation.duplicate_content.is_valid',
    detailsFieldPath: 'framework_state.validation.duplicate_content.message',
    policyUsable: true,
    packageUsable: true,
    requiresLatestRun: true,
    freshnessDefaultMinutes: 120,
    blockingDefault: false,
    warningOnlyDefault: true,
  }),
  Object.freeze({
    key: 'compliance-language-check',
    label: 'Compliance Language Check',
    description: 'Compliance Language Check validation definition for VMF v2.3.1.',
    status: VALIDATION_REGISTRY_STATUSES.ACTIVE,
    supportedFrameworkKeys: Object.freeze(['VMF']),
    category: VALIDATION_REGISTRY_CATEGORIES.GOVERNANCE,
    severity: VALIDATION_REGISTRY_SEVERITIES.ERROR,
    producerSkillId: 'skill-vmf-compliance-language-validator',
    defaultAgentIds: Object.freeze(['agent-vmf-governance-validator-agent']),
    outputPath: 'framework_state.validation.compliance_language',
    resultType: VALIDATION_REGISTRY_RESULT_TYPES.OBJECT,
    passFieldPath: 'framework_state.validation.compliance_language.is_valid',
    detailsFieldPath: 'framework_state.validation.compliance_language.message',
    policyUsable: true,
    packageUsable: true,
    requiresLatestRun: true,
    freshnessDefaultMinutes: 120,
    blockingDefault: true,
    warningOnlyDefault: false,
  }),
  Object.freeze({
    key: 'competitive-claim-risk-check',
    label: 'Competitive Claim Risk Check',
    description: 'Competitive Claim Risk Check validation definition for VMF v2.3.1.',
    status: VALIDATION_REGISTRY_STATUSES.ACTIVE,
    supportedFrameworkKeys: Object.freeze(['VMF']),
    category: VALIDATION_REGISTRY_CATEGORIES.GOVERNANCE,
    severity: VALIDATION_REGISTRY_SEVERITIES.WARNING,
    producerSkillId: 'skill-vmf-competitive-claim-risk-validator',
    defaultAgentIds: Object.freeze(['agent-vmf-governance-validator-agent']),
    outputPath: 'framework_state.validation.competitive_claim_risk',
    resultType: VALIDATION_REGISTRY_RESULT_TYPES.OBJECT,
    passFieldPath: 'framework_state.validation.competitive_claim_risk.is_valid',
    detailsFieldPath: 'framework_state.validation.competitive_claim_risk.message',
    policyUsable: true,
    packageUsable: true,
    requiresLatestRun: false,
    freshnessDefaultMinutes: 1440,
    blockingDefault: false,
    warningOnlyDefault: true,
  }),
  Object.freeze({
    key: 'approval-readiness-check',
    label: 'Approval Readiness Check',
    description: 'Approval Readiness Check validation definition for VMF v2.3.1.',
    status: VALIDATION_REGISTRY_STATUSES.ACTIVE,
    supportedFrameworkKeys: Object.freeze(['VMF']),
    category: VALIDATION_REGISTRY_CATEGORIES.GOVERNANCE,
    severity: VALIDATION_REGISTRY_SEVERITIES.ERROR,
    producerSkillId: 'skill-vmf-governance-completeness-validator',
    defaultAgentIds: Object.freeze(['agent-vmf-governance-validator-agent']),
    outputPath: 'framework_state.validation.governance_completeness',
    resultType: VALIDATION_REGISTRY_RESULT_TYPES.OBJECT,
    passFieldPath: 'framework_state.validation.governance_completeness.is_valid',
    detailsFieldPath: 'framework_state.validation.governance_completeness.message',
    policyUsable: true,
    packageUsable: true,
    requiresLatestRun: true,
    freshnessDefaultMinutes: 60,
    blockingDefault: true,
    warningOnlyDefault: false,
  }),
  Object.freeze({
    key: 'owner-assigned-check',
    label: 'Owner Assigned Check',
    description: 'Owner Assigned Check validation definition for VMF v2.3.1.',
    status: VALIDATION_REGISTRY_STATUSES.ACTIVE,
    supportedFrameworkKeys: Object.freeze(['VMF']),
    category: VALIDATION_REGISTRY_CATEGORIES.GOVERNANCE,
    severity: VALIDATION_REGISTRY_SEVERITIES.ERROR,
    producerSkillId: 'skill-vmf-owner-assigned-validator',
    defaultAgentIds: Object.freeze(['agent-vmf-governance-validator-agent']),
    outputPath: 'framework_state.validation.owner_assigned',
    resultType: VALIDATION_REGISTRY_RESULT_TYPES.OBJECT,
    passFieldPath: 'framework_state.validation.owner_assigned.is_valid',
    detailsFieldPath: 'framework_state.validation.owner_assigned.message',
    policyUsable: true,
    packageUsable: true,
    requiresLatestRun: false,
    freshnessDefaultMinutes: 1440,
    blockingDefault: true,
    warningOnlyDefault: false,
  }),
  Object.freeze({
    key: 'package-integrity-check',
    label: 'Package Integrity Check',
    description: 'Package Integrity Check validation definition for VMF v2.3.1.',
    status: VALIDATION_REGISTRY_STATUSES.ACTIVE,
    supportedFrameworkKeys: Object.freeze(['VMF']),
    category: VALIDATION_REGISTRY_CATEGORIES.GOVERNANCE,
    severity: VALIDATION_REGISTRY_SEVERITIES.ERROR,
    producerSkillId: 'skill-vmf-package-integrity-validator',
    defaultAgentIds: Object.freeze(['agent-vmf-governance-validator-agent']),
    outputPath: 'framework_state.validation.package_integrity',
    resultType: VALIDATION_REGISTRY_RESULT_TYPES.OBJECT,
    passFieldPath: 'framework_state.validation.package_integrity.is_valid',
    detailsFieldPath: 'framework_state.validation.package_integrity.message',
    policyUsable: true,
    packageUsable: true,
    requiresLatestRun: false,
    freshnessDefaultMinutes: 1440,
    blockingDefault: true,
    warningOnlyDefault: false,
  }),
])

export const validationRegistrySeedsByStage = Object.freeze({
  [VALIDATION_REGISTRY_SEED_STAGES.MVP]: VMF_V2_3_1_SEEDS,
  [VALIDATION_REGISTRY_SEED_STAGES.VMF_V2_3_1]: VMF_V2_3_1_SEEDS,
})

export const validationRegistrySeeds =
  validationRegistrySeedsByStage[VALIDATION_REGISTRY_SEED_STAGES.VMF_V2_3_1]
