export const DISCOVERY_ACQUISITION_PROFILES = Object.freeze({
  STANDARD: 'STANDARD',
  ENHANCED: 'ENHANCED',
  STRATEGIC: 'STRATEGIC',
})

export const ENABLED_DISCOVERY_ACQUISITION_PROFILES = Object.freeze([
  DISCOVERY_ACQUISITION_PROFILES.STANDARD,
])

export const RESERVED_DISCOVERY_ACQUISITION_PROFILES = Object.freeze([
  DISCOVERY_ACQUISITION_PROFILES.ENHANCED,
  DISCOVERY_ACQUISITION_PROFILES.STRATEGIC,
])

export const DISCOVERY_ACQUISITION_PROFILE_ERROR_MESSAGE =
  'acquisitionProfile must be STANDARD. ENHANCED and STRATEGIC are not available in this sprint.'
