export const KNOWLEDGE_PACK_PURPOSE_CATEGORIES = Object.freeze({
  GOVERNANCE: 'GOVERNANCE',
  OUTPUT: 'OUTPUT',
  FRAMEWORK: 'FRAMEWORK',
  DOMAIN: 'DOMAIN',
  VALIDATION: 'VALIDATION',
  STYLE: 'STYLE',
  AUDIENCE: 'AUDIENCE',
  INDUSTRY: 'INDUSTRY',
  LANGUAGE: 'LANGUAGE',
  BRAND: 'BRAND',
  COMPLIANCE: 'COMPLIANCE',
  DECISION: 'DECISION',
  ADVISOR: 'ADVISOR',
  CHANNEL: 'CHANNEL',
  COMMUNICATIONS: 'COMMUNICATIONS',
  VISUAL: 'VISUAL',
  TRANSFORMATION: 'TRANSFORMATION',
  CAPABILITY: 'CAPABILITY',
  PROCESS: 'PROCESS',
  ASSESSMENT: 'ASSESSMENT',
  REFERENCE: 'REFERENCE',
  SYSTEM: 'SYSTEM',
})

export const KNOWLEDGE_PACK_LAYERS = Object.freeze({
  FOUNDATION: 'FOUNDATION',
  DOMAIN: 'DOMAIN',
  SOLUTION: 'SOLUTION',
  ORGANISATION: 'ORGANISATION',
  RUNTIME: 'RUNTIME',
  SYSTEM: 'SYSTEM',
  REASONING: 'REASONING',
  FRAMEWORK: 'FRAMEWORK',
  AUDIENCE: 'AUDIENCE',
  INDUSTRY: 'INDUSTRY',
  OUTPUT_TYPE: 'OUTPUT_TYPE',
  OUTPUT_SCHEMA: 'OUTPUT_SCHEMA',
  COMMUNICATION_PATTERN: 'COMMUNICATION_PATTERN',
  STYLE: 'STYLE',
  CHANNEL: 'CHANNEL',
  BRAND: 'BRAND',
  LANGUAGE: 'LANGUAGE',
  VISUAL_SYSTEM: 'VISUAL_SYSTEM',
  VALIDATION: 'VALIDATION',
})

export const KNOWLEDGE_PACK_DEPENDENCY_REQUIREMENTS = Object.freeze({
  REQUIRED: 'REQUIRED',
  OPTIONAL: 'OPTIONAL',
})

export const KNOWLEDGE_PACK_RELATIONSHIP_CONTRACT_VERSION = 'SS002_RELATIONSHIP_V1'

export const KNOWLEDGE_PACK_RELATIONSHIP_TYPES = Object.freeze({
  REQUIRED_AT_ACTIVATION: 'REQUIRED_AT_ACTIVATION',
  REQUIRED_AT_RUNTIME: 'REQUIRED_AT_RUNTIME',
  OPTIONAL: 'OPTIONAL',
  COMPATIBLE_WITH: 'COMPATIBLE_WITH',
  SUPERSEDES: 'SUPERSEDES',
  REFERENCES: 'REFERENCES',
  REQUIRES_COMPATIBLE_PACK: 'REQUIRES_COMPATIBLE_PACK',
})

export const KNOWLEDGE_PACK_RELATIONSHIP_TIMINGS = Object.freeze({
  ACTIVATION: 'ACTIVATION',
  RUNTIME: 'RUNTIME',
  NONE: 'NONE',
})

export const KNOWLEDGE_PACK_RELATIONSHIP_CARDINALITIES = Object.freeze({
  ONE: 'ONE',
  ONE_OR_MORE: 'ONE_OR_MORE',
  ZERO_OR_ONE: 'ZERO_OR_ONE',
  ZERO_OR_MORE: 'ZERO_OR_MORE',
})

export const KNOWLEDGE_PACK_RELATIONSHIP_FAILURES = Object.freeze({
  MISSING_GOVERNANCE_METADATA: 'MISSING_GOVERNANCE_METADATA',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  MISSING_RELATIONSHIP: 'MISSING_RELATIONSHIP',
  INACTIVE_DEPENDENCY: 'INACTIVE_DEPENDENCY',
  AMBIGUOUS_DEPENDENCY: 'AMBIGUOUS_DEPENDENCY',
  INCOMPATIBLE_VERSION: 'INCOMPATIBLE_VERSION',
  CIRCULAR_DEPENDENCY: 'CIRCULAR_DEPENDENCY',
  DEPENDENCY_DEPTH_EXCEEDED: 'DEPENDENCY_DEPTH_EXCEEDED',
})

export const KNOWLEDGE_ASSET_ID_PATTERN_SOURCE = '[A-Z0-9]+(?:-[A-Z0-9]+)+'
export const KNOWLEDGE_ASSET_ID_PATTERN = new RegExp(`^${KNOWLEDGE_ASSET_ID_PATTERN_SOURCE}$`)

export const KNOWLEDGE_PACK_EXECUTION_MODES = Object.freeze({
  PROVIDER_CONTEXT: 'PROVIDER_CONTEXT',
  PRE_VALIDATION: 'PRE_VALIDATION',
  POST_VALIDATION: 'POST_VALIDATION',
  SYSTEM_ONLY: 'SYSTEM_ONLY',
})

export const KNOWLEDGE_PACK_VISIBILITY_SCOPES = Object.freeze({
  PLATFORM: 'PLATFORM',
  CUSTOMER: 'CUSTOMER',
  TENANT: 'TENANT',
})

export const KNOWLEDGE_PACK_AUTHORING_MODES = Object.freeze({
  IMPORT_SOURCE_DOCUMENT: 'IMPORT_SOURCE_DOCUMENT',
  CREATE_BLANK: 'CREATE_BLANK',
  TECHNICAL_IMPORT: 'TECHNICAL_IMPORT',
})

export const KNOWLEDGE_PACK_REVIEW_STATUSES = Object.freeze({
  DRAFT: 'DRAFT',
  READY_FOR_REVIEW: 'READY_FOR_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
})

export const KNOWLEDGE_PACK_MANIFEST_STATUSES = Object.freeze({
  DRAFT: 'DRAFT',
  VALIDATING: 'VALIDATING',
  VALIDATED: 'VALIDATED',
  ACTIVE: 'ACTIVE',
  DEPRECATED: 'DEPRECATED',
  DISABLED: 'DISABLED',
  FAILED_VALIDATION: 'FAILED_VALIDATION',
})

export const KNOWLEDGE_PACK_MANIFEST_TYPES = Object.freeze({
  OUTCOME_STUDIO_DEFAULT: 'OUTCOME_STUDIO_DEFAULT',
  FRAMEWORK_RUNTIME: 'FRAMEWORK_RUNTIME',
  OUTPUT_TYPE: 'OUTPUT_TYPE',
  VALIDATION: 'VALIDATION',
})

export const DEFAULT_OUTCOME_STUDIO_MANIFEST = Object.freeze({
  manifestKey: 'outcome-studio-default',
  manifestName: 'Outcome Studio Default Knowledge Manifest',
  semanticVersion: '1.0.0',
  manifestType: KNOWLEDGE_PACK_MANIFEST_TYPES.OUTCOME_STUDIO_DEFAULT,
})
