export const KNOWLEDGE_PACK_PURPOSE_CATEGORIES = Object.freeze({
  GOVERNANCE: 'GOVERNANCE',
  OUTPUT: 'OUTPUT',
  FRAMEWORK: 'FRAMEWORK',
  DOMAIN: 'DOMAIN',
  VALIDATION: 'VALIDATION',
  STYLE: 'STYLE',
  AUDIENCE: 'AUDIENCE',
  INDUSTRY: 'INDUSTRY',
  LANGUAGE: 'LANGUAGE',
  BRAND: 'BRAND',
  COMPLIANCE: 'COMPLIANCE',
  DECISION: 'DECISION',
  ADVISOR: 'ADVISOR',
  CHANNEL: 'CHANNEL',
  COMMUNICATIONS: 'COMMUNICATIONS',
  VISUAL: 'VISUAL',
  TRANSFORMATION: 'TRANSFORMATION',
  CAPABILITY: 'CAPABILITY',
  PROCESS: 'PROCESS',
  ASSESSMENT: 'ASSESSMENT',
  REFERENCE: 'REFERENCE',
  SYSTEM: 'SYSTEM',
})

export const KNOWLEDGE_PACK_LAYERS = Object.freeze({
  FOUNDATION: 'FOUNDATION',
  DOMAIN: 'DOMAIN',
  SOLUTION: 'SOLUTION',
  ORGANISATION: 'ORGANISATION',
  RUNTIME: 'RUNTIME',
  SYSTEM: 'SYSTEM',
  REASONING: 'REASONING',
  FRAMEWORK: 'FRAMEWORK',
  AUDIENCE: 'AUDIENCE',
  INDUSTRY: 'INDUSTRY',
  OUTPUT_TYPE: 'OUTPUT_TYPE',
  OUTPUT_SCHEMA: 'OUTPUT_SCHEMA',
  COMMUNICATION_PATTERN: 'COMMUNICATION_PATTERN',
  STYLE: 'STYLE',
  CHANNEL: 'CHANNEL',
  BRAND: 'BRAND',
  LANGUAGE: 'LANGUAGE',
  VISUAL_SYSTEM: 'VISUAL_SYSTEM',
  VALIDATION: 'VALIDATION',
})

export const KNOWLEDGE_PACK_DEPENDENCY_REQUIREMENTS = Object.freeze({
  REQUIRED: 'REQUIRED',
  OPTIONAL: 'OPTIONAL',
})

export const KNOWLEDGE_PACK_RELATIONSHIP_CONTRACT_VERSION = 'SS002_RELATIONSHIP_V1'

export const KNOWLEDGE_PACK_RELATIONSHIP_TYPES = Object.freeze({
  REQUIRED_AT_ACTIVATION: 'REQUIRED_AT_ACTIVATION',
  REQUIRED_AT_RUNTIME: 'REQUIRED_AT_RUNTIME',
  OPTIONAL: 'OPTIONAL',
  COMPATIBLE_WITH: 'COMPATIBLE_WITH',
  SUPERSEDES: 'SUPERSEDES',
  REFERENCES: 'REFERENCES',
  REQUIRES_COMPATIBLE_PACK: 'REQUIRES_COMPATIBLE_PACK',
})

export const KNOWLEDGE_PACK_RELATIONSHIP_TIMINGS = Object.freeze({
  ACTIVATION: 'ACTIVATION',
  RUNTIME: 'RUNTIME',
  NONE: 'NONE',
})

export const KNOWLEDGE_PACK_RELATIONSHIP_CARDINALITIES = Object.freeze({
  ONE: 'ONE',
  ONE_OR_MORE: 'ONE_OR_MORE',
  ZERO_OR_ONE: 'ZERO_OR_ONE',
  ZERO_OR_MORE: 'ZERO_OR_MORE',
})

export const KNOWLEDGE_PACK_RELATIONSHIP_FAILURES = Object.freeze({
  MISSING_GOVERNANCE_METADATA: 'MISSING_GOVERNANCE_METADATA',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  MISSING_RELATIONSHIP: 'MISSING_RELATIONSHIP',
  INACTIVE_DEPENDENCY: 'INACTIVE_DEPENDENCY',
  AMBIGUOUS_DEPENDENCY: 'AMBIGUOUS_DEPENDENCY',
  INCOMPATIBLE_VERSION: 'INCOMPATIBLE_VERSION',
  CIRCULAR_DEPENDENCY: 'CIRCULAR_DEPENDENCY',
  DEPENDENCY_DEPTH_EXCEEDED: 'DEPENDENCY_DEPTH_EXCEEDED',
})

export const KNOWLEDGE_ASSET_ID_PATTERN_SOURCE = '[A-Z0-9]+(?:-[A-Z0-9]+)+'
export const KNOWLEDGE_ASSET_ID_PATTERN = new RegExp(`^${KNOWLEDGE_ASSET_ID_PATTERN_SOURCE}$`)

export const KNOWLEDGE_PACK_EXECUTION_MODES = Object.freeze({
  PROVIDER_CONTEXT: 'PROVIDER_CONTEXT',
  PRE_VALIDATION: 'PRE_VALIDATION',
  POST_VALIDATION: 'POST_VALIDATION',
  SYSTEM_ONLY: 'SYSTEM_ONLY',
})

export const KNOWLEDGE_PACK_BOUNDARIES = Object.freeze({
  GENERATION_CONTEXT: 'GENERATION_CONTEXT',
  PRE_GENERATION_VALIDATION: 'PRE_GENERATION_VALIDATION',
  POST_GENERATION_VALIDATION: 'POST_GENERATION_VALIDATION',
  LINEAGE_CERTIFICATION: 'LINEAGE_CERTIFICATION',
})

export const KNOWLEDGE_PACK_RECEIPT_TYPES = Object.freeze({
  PROVIDER_EXECUTION: 'PROVIDER_EXECUTION',
  PRE_VALIDATION: 'PRE_VALIDATION',
  POST_VALIDATION: 'POST_VALIDATION',
  LINEAGE_CERTIFICATION: 'LINEAGE_CERTIFICATION',
})

const normalizeKnowledgeRuntimeToken = (value) => String(value ?? '').trim().toUpperCase()

export const resolveKnowledgePackBoundary = (pack = {}) => {
  const explicitBoundary = normalizeKnowledgeRuntimeToken(pack.boundary || pack.executionBoundary)
  if (Object.values(KNOWLEDGE_PACK_BOUNDARIES).includes(explicitBoundary)) return explicitBoundary

  const packType = normalizeKnowledgeRuntimeToken(pack.packType)
  const executionMode = normalizeKnowledgeRuntimeToken(pack.executionMode)
  // RL is a rendering/review concern and must not be admitted to the provider
  // writing context merely because older activation metadata still says
  // PROVIDER_CONTEXT. Explicit PRE/POST/SYSTEM metadata remains authoritative.
  if (packType === 'RL' && executionMode === KNOWLEDGE_PACK_EXECUTION_MODES.PROVIDER_CONTEXT) {
    return KNOWLEDGE_PACK_BOUNDARIES.POST_GENERATION_VALIDATION
  }

  switch (executionMode) {
    case KNOWLEDGE_PACK_EXECUTION_MODES.PROVIDER_CONTEXT:
      return KNOWLEDGE_PACK_BOUNDARIES.GENERATION_CONTEXT
    case KNOWLEDGE_PACK_EXECUTION_MODES.PRE_VALIDATION:
    case KNOWLEDGE_PACK_EXECUTION_MODES.SYSTEM_ONLY:
      return KNOWLEDGE_PACK_BOUNDARIES.PRE_GENERATION_VALIDATION
    case KNOWLEDGE_PACK_EXECUTION_MODES.POST_VALIDATION:
      return KNOWLEDGE_PACK_BOUNDARIES.POST_GENERATION_VALIDATION
    default:
      if (packType === 'ARL') return KNOWLEDGE_PACK_BOUNDARIES.GENERATION_CONTEXT
      if (packType === 'RL') return KNOWLEDGE_PACK_BOUNDARIES.POST_GENERATION_VALIDATION
      return ''
  }
}

export const resolveKnowledgePackReceiptType = (pack = {}) => {
  switch (resolveKnowledgePackBoundary(pack)) {
    case KNOWLEDGE_PACK_BOUNDARIES.GENERATION_CONTEXT:
      return KNOWLEDGE_PACK_RECEIPT_TYPES.PROVIDER_EXECUTION
    case KNOWLEDGE_PACK_BOUNDARIES.PRE_GENERATION_VALIDATION:
      return KNOWLEDGE_PACK_RECEIPT_TYPES.PRE_VALIDATION
    case KNOWLEDGE_PACK_BOUNDARIES.POST_GENERATION_VALIDATION:
      return KNOWLEDGE_PACK_RECEIPT_TYPES.POST_VALIDATION
    case KNOWLEDGE_PACK_BOUNDARIES.LINEAGE_CERTIFICATION:
      return KNOWLEDGE_PACK_RECEIPT_TYPES.LINEAGE_CERTIFICATION
    default:
      return ''
  }
}

export const KNOWLEDGE_PACK_VISIBILITY_SCOPES = Object.freeze({
  PLATFORM: 'PLATFORM',
  CUSTOMER: 'CUSTOMER',
  TENANT: 'TENANT',
})

export const KNOWLEDGE_PACK_AUTHORING_MODES = Object.freeze({
  IMPORT_SOURCE_DOCUMENT: 'IMPORT_SOURCE_DOCUMENT',
  CREATE_BLANK: 'CREATE_BLANK',
  TECHNICAL_IMPORT: 'TECHNICAL_IMPORT',
})

export const KNOWLEDGE_PACK_REVIEW_STATUSES = Object.freeze({
  DRAFT: 'DRAFT',
  READY_FOR_REVIEW: 'READY_FOR_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
})

export const KNOWLEDGE_PACK_MANIFEST_STATUSES = Object.freeze({
  DRAFT: 'DRAFT',
  VALIDATING: 'VALIDATING',
  VALIDATED: 'VALIDATED',
  ACTIVE: 'ACTIVE',
  DEPRECATED: 'DEPRECATED',
  DISABLED: 'DISABLED',
  FAILED_VALIDATION: 'FAILED_VALIDATION',
})

export const KNOWLEDGE_PACK_MANIFEST_TYPES = Object.freeze({
  OUTCOME_STUDIO_DEFAULT: 'OUTCOME_STUDIO_DEFAULT',
  FRAMEWORK_RUNTIME: 'FRAMEWORK_RUNTIME',
  OUTPUT_TYPE: 'OUTPUT_TYPE',
  VALIDATION: 'VALIDATION',
})

export const DEFAULT_OUTCOME_STUDIO_MANIFEST = Object.freeze({
  manifestKey: 'outcome-studio-default',
  manifestName: 'Outcome Studio Default Knowledge Manifest',
  semanticVersion: '1.0.0',
  manifestType: KNOWLEDGE_PACK_MANIFEST_TYPES.OUTCOME_STUDIO_DEFAULT,
})
