export const OUTCOME_KNOWLEDGE_PACK_TYPES = Object.freeze({
  ARL: 'ARL',
  RL: 'RL',
  OUTPUT_SCHEMA: 'OUTPUT_SCHEMA',
  TRUTH_CERTIFICATION: 'TRUTH_CERTIFICATION',
  OUTPUT_TYPE_DEFINITION: 'OUTPUT_TYPE_DEFINITION',
})

export const OUTCOME_KNOWLEDGE_PACK_STATUSES = Object.freeze({
  DRAFT: 'DRAFT',
  VALIDATING: 'VALIDATING',
  VALIDATED: 'VALIDATED',
  ACTIVE: 'ACTIVE',
  DEPRECATED: 'DEPRECATED',
  DISABLED: 'DISABLED',
  FAILED_VALIDATION: 'FAILED_VALIDATION',
  ROLLED_BACK: 'ROLLED_BACK',
})

export const OUTCOME_KNOWLEDGE_PACK_CONTENT_FORMATS = Object.freeze({
  YAML: 'YAML',
  JSON: 'JSON',
})

export const OUTCOME_KNOWLEDGE_PACK_ACTIVATION_STATUSES = Object.freeze({
  ACTIVE: 'ACTIVE',
  DEPRECATED: 'DEPRECATED',
  DISABLED: 'DISABLED',
  ROLLED_BACK: 'ROLLED_BACK',
})

export const OUTCOME_KNOWLEDGE_PACK_SCOPE_TYPES = Object.freeze({
  GLOBAL: 'GLOBAL',
  FRAMEWORK: 'FRAMEWORK',
  RUNTIME_TYPE: 'RUNTIME_TYPE',
  PACKAGE: 'PACKAGE',
  ENVIRONMENT: 'ENVIRONMENT',
  CUSTOMER: 'CUSTOMER',
  TENANT: 'TENANT',
  RUNTIME_INSTANCE: 'RUNTIME_INSTANCE',
})

export const OUTCOME_KNOWLEDGE_PACK_SOURCE_BUNDLE_PATH =
  'docs/product-specs/source-artifacts/2026-06-15-governed-outcome-studio-oes-002/knowledge-packs-v1/'

export const OUTCOME_KNOWLEDGE_PACK_RESOLUTION_MODE = 'REGISTRY_RESOLUTION'
