import { OUTCOME_STUDIO_REFERENCE_FAMILIES } from './outcomeStudioReadiness.js'

export { OUTCOME_STUDIO_REFERENCE_FAMILIES }

export const OUTCOME_STUDIO_TEST_REFERENCE_STATUSES = Object.freeze({
  DRAFT: 'DRAFT',
  APPROVED: 'APPROVED',
  SUPERSEDED: 'SUPERSEDED',
})

export const OUTCOME_STUDIO_TEST_REFERENCE_FORMAT = Object.freeze({
  EXTENSION: '.pdf',
  MIME_TYPE: 'application/pdf',
})

export const OUTCOME_STUDIO_TEST_REFERENCE_LIMITS = Object.freeze({
  MAX_RAW_BYTES: 10_000_000,
  MAX_BASE64_CHARACTERS: 13_333_336,
  MAX_TITLE_LENGTH: 200,
  MAX_PURPOSE_LENGTH: 1000,
  MAX_FILENAME_LENGTH: 255,
  MAX_ACTOR_NAME_LENGTH: 160,
  MAX_ACTOR_EMAIL_LENGTH: 254,
  MAX_RATIONALE_LENGTH: 1000,
  MAX_PAGE: 1_000_000,
  MAX_PAGE_SIZE: 100,
})

export const OUTCOME_STUDIO_TEST_REFERENCE_ERROR_CODES = Object.freeze({
  VALIDATION_FAILED: 'OUTCOME_STUDIO_TEST_REFERENCE_VALIDATION_FAILED',
  NOT_FOUND: 'OUTCOME_STUDIO_TEST_REFERENCE_NOT_FOUND',
  REVISION_CONFLICT: 'OUTCOME_STUDIO_TEST_REFERENCE_REVISION_CONFLICT',
  TRANSITION_INVALID: 'OUTCOME_STUDIO_TEST_REFERENCE_TRANSITION_INVALID',
  OBJECT_MISSING: 'OUTCOME_STUDIO_TEST_REFERENCE_OBJECT_MISSING',
  OBJECT_CORRUPT: 'OUTCOME_STUDIO_TEST_REFERENCE_OBJECT_CORRUPT',
  TRANSACTION_REQUIRED: 'OUTCOME_STUDIO_TEST_REFERENCE_TRANSACTION_REQUIRED',
  AUDIT_FAILED: 'OUTCOME_STUDIO_TEST_REFERENCE_AUDIT_FAILED',
  PERSISTENCE_FAILED: 'OUTCOME_STUDIO_TEST_REFERENCE_PERSISTENCE_FAILED',
  IMMUTABLE: 'OUTCOME_STUDIO_TEST_REFERENCE_IMMUTABLE',
})
