export const OUTCOME_STUDIO_READINESS_REGISTER_ID = 'oes-004-r2-slice-5-application-readiness-test'
export const OUTCOME_STUDIO_READINESS_COMPONENT_ID = 'outcome-studio-readiness-administration'
export const OUTCOME_STUDIO_READINESS_ENVIRONMENT = 'TEST'

export const OUTCOME_STUDIO_READINESS_POLICY_VERSIONS = Object.freeze({
  LEGACY: 'LEGACY_SLICE_5A_V1',
  DEVELOPMENT_TEST: 'OES_004_DEVELOPMENT_TEST_READINESS_V1',
})

export const OUTCOME_STUDIO_READINESS_VERDICTS = Object.freeze({
  READY: 'SLICE_5_APPLICATION_READY',
  BLOCKED: 'SLICE_5_APPLICATION_BLOCKED',
})

export const OUTCOME_STUDIO_DEVELOPMENT_TEST_READINESS_VERDICTS = Object.freeze({
  READY: 'READY_FOR_TESTING',
  BLOCKED: 'BLOCKED_FOR_TESTING',
})

export const OUTCOME_STUDIO_DEVELOPMENT_TEST_GATES = Object.freeze([
  'QUALITY_RUBRIC',
  'TEST_REFERENCE_EXAMPLES',
  'SAFE_PROVIDER_POLICY',
  'PRODUCT_TESTING_APPROVAL',
])

export const OUTCOME_STUDIO_DEVELOPMENT_TEST_BLOCKERS = Object.freeze({
  QUALITY_RUBRIC: 'QUALITY_RUBRIC_BLOCKED',
  TEST_REFERENCE_EXAMPLES: 'TEST_REFERENCE_EXAMPLES_BLOCKED',
  SAFE_PROVIDER_POLICY: 'SAFE_PROVIDER_POLICY_BLOCKED',
  PRODUCT_TESTING_APPROVAL: 'PRODUCT_TESTING_APPROVAL_BLOCKED',
})

export const OUTCOME_STUDIO_PROVIDER_SAFE_CONTEXT_POLICY = 'OUTCOME_STUDIO_PROVIDER_SAFE_CONTEXT_V1'
export const OUTCOME_STUDIO_TESTING_PURPOSE = 'CONTROLLED_TEST_ENGINEERING_VALIDATION'

export const OUTCOME_STUDIO_READINESS_ERROR_CODES = Object.freeze({
  VALIDATION_FAILED: 'OUTCOME_STUDIO_READINESS_VALIDATION_FAILED',
  REVISION_CONFLICT: 'OUTCOME_STUDIO_READINESS_REVISION_CONFLICT',
  CURRENT_REVISION_MISSING: 'OUTCOME_STUDIO_READINESS_CURRENT_REVISION_MISSING',
  POLICY_TRANSITION_INVALID: 'OUTCOME_STUDIO_READINESS_POLICY_TRANSITION_INVALID',
  TRANSACTION_REQUIRED: 'OUTCOME_STUDIO_READINESS_TRANSACTION_REQUIRED',
  TEST_REFERENCE_RESOLUTION_FAILED: 'OUTCOME_STUDIO_TEST_REFERENCE_RESOLUTION_FAILED',
  PERSISTENCE_FAILED: 'OUTCOME_STUDIO_READINESS_PERSISTENCE_FAILED',
  AUDIT_FAILED: 'OUTCOME_STUDIO_READINESS_AUDIT_FAILED',
})

export const OUTCOME_STUDIO_READINESS_STATUSES = Object.freeze({
  OPEN: 'OPEN',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
})

export const OUTCOME_STUDIO_REFERENCE_FAMILIES = Object.freeze([
  'PROFESSIONAL_DOCUMENT',
  'PRESENTATION',
  'INFOGRAPHIC',
])

export const OUTCOME_STUDIO_READINESS_DECISION_KEYS = Object.freeze({
  PROVIDER_POSTURE: 'PROVIDER_POSTURE',
  PROVIDER_SAFE_CONTEXT: 'PROVIDER_SAFE_CONTEXT',
  IMPLEMENTATION_TEST_ACKNOWLEDGEMENT: 'IMPLEMENTATION_TEST_ACKNOWLEDGEMENT',
})

export const OUTCOME_STUDIO_READINESS_AUTHORITY_MATRIX = Object.freeze({
  [OUTCOME_STUDIO_READINESS_DECISION_KEYS.PROVIDER_POSTURE]: Object.freeze([
    'PRODUCT_OWNER', 'SECURITY', 'LEGAL', 'COMMERCIAL',
  ]),
  [OUTCOME_STUDIO_READINESS_DECISION_KEYS.PROVIDER_SAFE_CONTEXT]: Object.freeze([
    'ARCHITECTURE', 'SECURITY',
  ]),
  [OUTCOME_STUDIO_READINESS_DECISION_KEYS.IMPLEMENTATION_TEST_ACKNOWLEDGEMENT]: Object.freeze([
    'ENGINEERING', 'QA',
  ]),
})

export const OUTCOME_STUDIO_READINESS_BLOCKERS = Object.freeze({
  REFERENCE_FAMILY_NOT_APPROVED: 'REFERENCE_FAMILY_NOT_APPROVED',
  REFERENCE_EVIDENCE_INCOMPLETE: 'REFERENCE_EVIDENCE_INCOMPLETE',
  REFERENCE_FAMILY_DUPLICATE: 'REFERENCE_FAMILY_DUPLICATE',
  RUBRIC_NOT_APPROVED: 'RUBRIC_NOT_APPROVED',
  RUBRIC_THRESHOLD_MISSING: 'RUBRIC_THRESHOLD_MISSING',
  PRIMARY_REVIEWER_MISSING: 'PRIMARY_REVIEWER_MISSING',
  RUBRIC_PROVENANCE_INVALID: 'RUBRIC_PROVENANCE_INVALID',
  PROVIDER_POSTURE_INCOMPLETE: 'PROVIDER_POSTURE_INCOMPLETE',
  PROVIDER_FAILURE_POSTURE_INVALID: 'PROVIDER_FAILURE_POSTURE_INVALID',
  PROVIDER_ENVIRONMENT_INVALID: 'PROVIDER_ENVIRONMENT_INVALID',
  REQUIRED_AUTHORITY_NOT_APPROVED: 'REQUIRED_AUTHORITY_NOT_APPROVED',
  AUTHORITY_PROVENANCE_INVALID: 'AUTHORITY_PROVENANCE_INVALID',
  AUTHORITY_ENTRY_DUPLICATE: 'AUTHORITY_ENTRY_DUPLICATE',
  DECISION_KEY_DUPLICATE: 'DECISION_KEY_DUPLICATE',
})

export const OUTCOME_STUDIO_READINESS_LIMITS = Object.freeze({
  MAX_BODY_BYTES: 64 * 1024,
  MAX_STRING_LENGTH: 500,
  MAX_NOTE_LENGTH: 1000,
  MAX_KEY_LENGTH: 140,
  MAX_VERSION_LENGTH: 80,
  MAX_MODEL_LENGTH: 160,
  MAX_ACTOR_LENGTH: 160,
  MAX_RATIONALE_LENGTH: 1000,
  MAX_ARRAY_LENGTH: 20,
  MAX_DEPTH: 8,
})
