export const OUTCOME_KNOWLEDGE_PACK_TYPES = Object.freeze({
  ARL: 'ARL',
  RL: 'RL',
  ET: 'ET',
  ET_RT: 'ET_RT',
  ERR: 'ERR',
  RGS: 'RGS',
  OR: 'OR',
  CCD: 'CCD',
  CCR: 'CCR',
  DX: 'DX',
  VE: 'VE',
  CR: 'CR',
  CDRM: 'CDRM',
  CDRT: 'CDRT',
  FRAMEWORK_METADATA: 'FRAMEWORK_METADATA',
  FRAMEWORK_PACK: 'FRAMEWORK_PACK',
  SYSTEM_REFERENCE: 'SYSTEM_REFERENCE',
  OUTPUT_SCHEMA: 'OUTPUT_SCHEMA',
  TRUTH_CERTIFICATION: 'TRUTH_CERTIFICATION',
  OUTPUT_TYPE_DEFINITION: 'OUTPUT_TYPE_DEFINITION',
  STYLE: 'STYLE',
  AUDIENCE: 'AUDIENCE',
  INDUSTRY: 'INDUSTRY',
  LANGUAGE: 'LANGUAGE',
  BRAND: 'BRAND',
  COMPLIANCE: 'COMPLIANCE',
  DECISION: 'DECISION',
  ADVISOR: 'ADVISOR',
  DOMAIN: 'DOMAIN',
  SYSTEM: 'SYSTEM',
})

export const OUTCOME_KNOWLEDGE_PACK_STATUSES = Object.freeze({
  DRAFT: 'DRAFT',
  VALIDATING: 'VALIDATING',
  VALIDATED: 'VALIDATED',
  ACTIVE: 'ACTIVE',
  DEPRECATED: 'DEPRECATED',
  DISABLED: 'DISABLED',
  FAILED_VALIDATION: 'FAILED_VALIDATION',
  ROLLED_BACK: 'ROLLED_BACK',
})

export const OUTCOME_KNOWLEDGE_PACK_CONTENT_FORMATS = Object.freeze({
  YAML: 'YAML',
  JSON: 'JSON',
  MARKDOWN: 'MARKDOWN',
  DOCX: 'DOCX',
  PDF: 'PDF',
})

export const OUTCOME_KNOWLEDGE_PACK_ACTIVATION_STATUSES = Object.freeze({
  ACTIVE: 'ACTIVE',
  DEPRECATED: 'DEPRECATED',
  DISABLED: 'DISABLED',
  ROLLED_BACK: 'ROLLED_BACK',
})

export const OUTCOME_KNOWLEDGE_PACK_SCOPE_TYPES = Object.freeze({
  GLOBAL: 'GLOBAL',
  FRAMEWORK: 'FRAMEWORK',
  RUNTIME_TYPE: 'RUNTIME_TYPE',
  PACKAGE: 'PACKAGE',
  ENVIRONMENT: 'ENVIRONMENT',
  CUSTOMER: 'CUSTOMER',
  TENANT: 'TENANT',
  RUNTIME_INSTANCE: 'RUNTIME_INSTANCE',
})

export const OUTCOME_KNOWLEDGE_PACK_RESOLUTION_MODE = 'REGISTRY_RESOLUTION'
