export const OUTCOME_GOVERNED_QUALITY_CONTRACT_VERSION = 'fs-003-quality-chain.v0.2'
export const OUTCOME_ACCEPTED_TRUTH_IDENTITY_CONTRACT_VERSION = 'fs-003-accepted-truth-identity.v1'

export const OUTCOME_KCP_STATUSES = Object.freeze({
  READY: 'READY',
  READY_WITH_GAPS: 'READY_WITH_GAPS',
  BLOCKED: 'BLOCKED',
})

export const OUTCOME_KCP_OPERATIONS = Object.freeze({
  INITIAL: 'INITIAL',
  RE_RESOLUTION: 'RE_RESOLUTION',
})

export const OUTCOME_QUALITY_STAGES = Object.freeze({
  FRAMEWORK_GUIDANCE: 'FRAMEWORK_GUIDANCE',
  WORKING_DRAFT: 'WORKING_DRAFT',
  ARL_MEANING_REVIEW: 'ARL_MEANING_REVIEW',
  OUTCOME_NARRATIVE_PLAN: 'OUTCOME_NARRATIVE_PLAN',
  OUTPUT_SHAPING: 'OUTPUT_SHAPING',
  RENDERED_EXPRESSION_RL: 'RENDERED_EXPRESSION_RL',
  CANDIDATE_DISPOSITION: 'CANDIDATE_DISPOSITION',
})

export const OUTCOME_QUALITY_STAGE_SEQUENCE = Object.freeze([
  OUTCOME_QUALITY_STAGES.FRAMEWORK_GUIDANCE,
  OUTCOME_QUALITY_STAGES.WORKING_DRAFT,
  OUTCOME_QUALITY_STAGES.ARL_MEANING_REVIEW,
  OUTCOME_QUALITY_STAGES.OUTCOME_NARRATIVE_PLAN,
  OUTCOME_QUALITY_STAGES.OUTPUT_SHAPING,
  OUTCOME_QUALITY_STAGES.RENDERED_EXPRESSION_RL,
  OUTCOME_QUALITY_STAGES.CANDIDATE_DISPOSITION,
])

export const OUTCOME_QUALITY_STAGE_STATUSES = Object.freeze({
  SUCCEEDED: 'SUCCEEDED',
  BLOCKED: 'BLOCKED',
  FAILED: 'FAILED',
})

export const OUTCOME_QUALITY_STAGE_OUTPUT_TYPES = Object.freeze({
  FRAMEWORK_GUIDANCE_ANALYSIS: 'FRAMEWORK_GUIDANCE_ANALYSIS',
  WORKING_DRAFT: 'WORKING_DRAFT',
  ARL_MEANING_REVIEW: 'ARL_MEANING_REVIEW',
  OUTCOME_NARRATIVE_PLAN: 'OUTCOME_NARRATIVE_PLAN',
  RENDERED_EXPRESSION: 'RENDERED_EXPRESSION',
  RENDERED_EXPRESSION_RL: 'RENDERED_EXPRESSION_RL',
})

export const OUTCOME_FRAMEWORK_GUIDANCE_SCHEMA_VERSION = 'fs-003-framework-guidance-analysis.v0.2'
export const OUTCOME_WORKING_DRAFT_SCHEMA_VERSION = 'fs-003-working-draft.v0.3'
export const OUTCOME_WORKING_DRAFT_VALIDATION_STATUSES = Object.freeze([
  'NOT_STATED',
  'SOURCE_REPORTED_VALIDATED',
  'SOURCE_REPORTED_REQUIRES_VALIDATION',
])
export const OUTCOME_WORKING_DRAFT_PROOF_DISPOSITIONS = Object.freeze([
  'NOT_ESTABLISHED',
  'SOURCE_SPECIFIED',
  'AUTHOR_PROPOSED',
])
export const OUTCOME_FRAMEWORK_GUIDANCE_PROVIDER_RESPONSE_SCHEMA_NAME = 'framework_guidance_analysis_v2'
export const OUTCOME_WORKING_DRAFT_PROVIDER_RESPONSE_SCHEMA_NAME = 'fs_003_working_draft_v0_3'
export const OUTCOME_ARL_MEANING_REVIEW_SCHEMA_VERSION = 'fs-003-arl-meaning-review.v0.2'
export const OUTCOME_ARL_MEANING_REVIEW_PROVIDER_RESPONSE_SCHEMA_NAME = 'fs_003_arl_meaning_review_v0_2'
export const OUTCOME_ARL_MEANING_REVIEW_PROVIDER_CONFIG_VERSIONS = Object.freeze({
  OPENAI_RESPONSES_V2: 'OUTCOME_ARL_MEANING_REVIEW_OPENAI_RESPONSES_V2',
  OPENAI_RESPONSES_V3_FRAMEWORK_PROOF_SEQUENCE:
    'OUTCOME_ARL_MEANING_REVIEW_OPENAI_RESPONSES_V3_FRAMEWORK_PROOF_SEQUENCE',
  OPENAI_RESPONSES_V4_STRUCTURED_REALITY_BOUNDARIES:
    'OUTCOME_ARL_MEANING_REVIEW_OPENAI_RESPONSES_V4_STRUCTURED_REALITY_BOUNDARIES',
})
export const OUTCOME_ARL_MEANING_REVIEW_PROVIDER_CONFIG_VERSION =
  OUTCOME_ARL_MEANING_REVIEW_PROVIDER_CONFIG_VERSIONS.OPENAI_RESPONSES_V4_STRUCTURED_REALITY_BOUNDARIES
export const OUTCOME_ARL_MEANING_REVIEW_PROVIDER_SAFE_CONTEXT_VERSION =
  'ss-033-arl-meaning-review-provider-safe-context.v2'
export const OUTCOME_NARRATIVE_PLAN_SCHEMA_VERSION = 'fs-003-outcome-narrative-plan.v0.2'
export const OUTCOME_RENDERED_EXPRESSION_SCHEMA_VERSION = 'fs-003-rendered-expression.v0.2'
export const OUTCOME_RENDERED_EXPRESSION_RL_SCHEMA_VERSION = 'fs-003-rendered-expression-rl.v0.2'
export const OUTCOME_RENDERED_EXPRESSION_RL_PROVIDER_RESPONSE_SCHEMA_NAME =
  'fs_003_rendered_expression_rl_v0_2'
export const OUTCOME_QUALITY_STAGE_PROVIDER_SAFE_CONTEXT_VERSION =
  'fs-003-quality-stage-provider-safe-context.v0.2'
export const OUTCOME_RENDERED_EXPRESSION_RL_PROVIDER_SAFE_CONTEXT_VERSION =
  'fs-003-rendered-expression-rl-provider-safe-context.v0.2'

export const OUTCOME_FRAMEWORK_GUIDANCE_PROVIDER_CONFIG_VERSIONS = Object.freeze({
  OPENAI_RESPONSES_V1: 'OUTCOME_FRAMEWORK_GUIDANCE_OPENAI_RESPONSES_V1',
  OPENAI_RESPONSES_V2: 'OUTCOME_FRAMEWORK_GUIDANCE_OPENAI_RESPONSES_V2',
  OPENAI_RESPONSES_V3_BACKGROUND: 'OUTCOME_FRAMEWORK_GUIDANCE_OPENAI_RESPONSES_V3_BACKGROUND',
  OPENAI_RESPONSES_V4_SAFE_OUTPUT_DIAGNOSTICS:
    'OUTCOME_FRAMEWORK_GUIDANCE_OPENAI_RESPONSES_V4_SAFE_OUTPUT_DIAGNOSTICS',
  OPENAI_RESPONSES_V5_SEMANTIC_CLAIM_CALIBRATION:
    'OUTCOME_FRAMEWORK_GUIDANCE_OPENAI_RESPONSES_V5_SEMANTIC_CLAIM_CALIBRATION',
  OPENAI_RESPONSES_V6_ARL_BOUNDARY_DIAGNOSTICS:
    'OUTCOME_FRAMEWORK_GUIDANCE_OPENAI_RESPONSES_V6_ARL_BOUNDARY_DIAGNOSTICS',
  OPENAI_RESPONSES_V7_REALITY_BOUNDARIES:
    'OUTCOME_FRAMEWORK_GUIDANCE_OPENAI_RESPONSES_V7_REALITY_BOUNDARIES',
  OPENAI_RESPONSES_V8_SINGLE_LINE_TEXT:
    'OUTCOME_FRAMEWORK_GUIDANCE_OPENAI_RESPONSES_V8_SINGLE_LINE_TEXT',
})

export const OUTCOME_FRAMEWORK_GUIDANCE_PROVIDER_CONFIG_VERSION =
  OUTCOME_FRAMEWORK_GUIDANCE_PROVIDER_CONFIG_VERSIONS.OPENAI_RESPONSES_V8_SINGLE_LINE_TEXT

export const OUTCOME_WORKING_DRAFT_PROVIDER_CONFIG_VERSIONS = Object.freeze({
  OPENAI_RESPONSES_V1: 'OUTCOME_WORKING_DRAFT_OPENAI_RESPONSES_V1',
  OPENAI_RESPONSES_V2_REALITY_BOUNDARIES:
    'OUTCOME_WORKING_DRAFT_OPENAI_RESPONSES_V2_REALITY_BOUNDARIES',
  OPENAI_RESPONSES_V3_CLAIM_COVERAGE:
    'OUTCOME_WORKING_DRAFT_OPENAI_RESPONSES_V3_CLAIM_COVERAGE',
  OPENAI_RESPONSES_V4_DECISION_MEANING:
    'OUTCOME_WORKING_DRAFT_OPENAI_RESPONSES_V4_DECISION_MEANING',
  OPENAI_RESPONSES_V5_MEANING_BOUNDARY:
    'OUTCOME_WORKING_DRAFT_OPENAI_RESPONSES_V5_MEANING_BOUNDARY',
  OPENAI_RESPONSES_V6_MEANING_SEQUENCE:
    'OUTCOME_WORKING_DRAFT_OPENAI_RESPONSES_V6_MEANING_SEQUENCE',
  OPENAI_RESPONSES_V7_BOUNDED_SUPPORTING_TEXT:
    'OUTCOME_WORKING_DRAFT_OPENAI_RESPONSES_V7_BOUNDED_SUPPORTING_TEXT',
  OPENAI_RESPONSES_V8_ARL_MEANING_BOUNDARY:
    'OUTCOME_WORKING_DRAFT_OPENAI_RESPONSES_V8_ARL_MEANING_BOUNDARY',
  OPENAI_RESPONSES_V9_BOUNDED_INTERIM_DECISIONS:
    'OUTCOME_WORKING_DRAFT_OPENAI_RESPONSES_V9_BOUNDED_INTERIM_DECISIONS',
  OPENAI_RESPONSES_V10_OPEN_PROOF_DESIGN:
    'OUTCOME_WORKING_DRAFT_OPENAI_RESPONSES_V10_OPEN_PROOF_DESIGN',
  OPENAI_RESPONSES_V11_EVIDENCE_ANCHORED_NARRATIVE:
    'OUTCOME_WORKING_DRAFT_OPENAI_RESPONSES_V11_EVIDENCE_ANCHORED_NARRATIVE',
  OPENAI_RESPONSES_V12_PROOF_ORDER_NOT_PRIORITY:
    'OUTCOME_WORKING_DRAFT_OPENAI_RESPONSES_V12_PROOF_ORDER_NOT_PRIORITY',
  OPENAI_RESPONSES_V13_PROVISIONAL_PROOF_TRIAGE:
    'OUTCOME_WORKING_DRAFT_OPENAI_RESPONSES_V13_PROVISIONAL_PROOF_TRIAGE',
  OPENAI_RESPONSES_V14_CUSTOMER_GROUNDED_SECTIONS:
    'OUTCOME_WORKING_DRAFT_OPENAI_RESPONSES_V14_CUSTOMER_GROUNDED_SECTIONS',
  OPENAI_RESPONSES_V15_FRAMEWORK_PROOF_SEQUENCE:
    'OUTCOME_WORKING_DRAFT_OPENAI_RESPONSES_V15_FRAMEWORK_PROOF_SEQUENCE',
  OPENAI_RESPONSES_V16_BOUNDED_PROOF_METADATA:
    'OUTCOME_WORKING_DRAFT_OPENAI_RESPONSES_V16_BOUNDED_PROOF_METADATA',
  OPENAI_RESPONSES_V17_CONDITIONAL_PROOF_BOUNDARIES:
    'OUTCOME_WORKING_DRAFT_OPENAI_RESPONSES_V17_CONDITIONAL_PROOF_BOUNDARIES',
  OPENAI_RESPONSES_V18_SCHEMA_GUIDED_BOUNDARIES:
    'OUTCOME_WORKING_DRAFT_OPENAI_RESPONSES_V18_SCHEMA_GUIDED_BOUNDARIES',
  OPENAI_RESPONSES_V19_STRUCTURED_REALITY_BOUNDARIES:
    'OUTCOME_WORKING_DRAFT_OPENAI_RESPONSES_V19_STRUCTURED_REALITY_BOUNDARIES',
  OPENAI_RESPONSES_V20_QUALIFIED_PROSE_ALIGNMENT:
    'OUTCOME_WORKING_DRAFT_OPENAI_RESPONSES_V20_QUALIFIED_PROSE_ALIGNMENT',
  OPENAI_RESPONSES_V21_ARL_BOUNDARY_REMAINDER:
    'OUTCOME_WORKING_DRAFT_OPENAI_RESPONSES_V21_ARL_BOUNDARY_REMAINDER',
  OPENAI_RESPONSES_V22_EXPLICIT_BOUNDARY_EXAMPLES:
    'OUTCOME_WORKING_DRAFT_OPENAI_RESPONSES_V22_EXPLICIT_BOUNDARY_EXAMPLES',
  OPENAI_RESPONSES_V23_SECTION_GAP_EXAMPLE:
    'OUTCOME_WORKING_DRAFT_OPENAI_RESPONSES_V23_SECTION_GAP_EXAMPLE',
  OPENAI_RESPONSES_V24_SECTION_GAP_BOUNDARY_WORDING:
    'OUTCOME_WORKING_DRAFT_OPENAI_RESPONSES_V24_SECTION_GAP_BOUNDARY_WORDING',
  OPENAI_RESPONSES_V25_GLOBAL_BOUNDARY_WORDING:
    'OUTCOME_WORKING_DRAFT_OPENAI_RESPONSES_V25_GLOBAL_BOUNDARY_WORDING',
  OPENAI_RESPONSES_V26_ARL_FINDING_ALIGNMENT:
    'OUTCOME_WORKING_DRAFT_OPENAI_RESPONSES_V26_ARL_FINDING_ALIGNMENT',
  OPENAI_RESPONSES_V27_EXPLICIT_OMISSION_WORDING:
    'OUTCOME_WORKING_DRAFT_OPENAI_RESPONSES_V27_EXPLICIT_OMISSION_WORDING',
  OPENAI_RESPONSES_V28_ENVIRONMENTAL_ATTRIBUTION:
    'OUTCOME_WORKING_DRAFT_OPENAI_RESPONSES_V28_ENVIRONMENTAL_ATTRIBUTION',
  OPENAI_RESPONSES_V29_ARL_COHERENCE_BOUNDARIES:
    'OUTCOME_WORKING_DRAFT_OPENAI_RESPONSES_V29_ARL_COHERENCE_BOUNDARIES',
  OPENAI_RESPONSES_V30_SYNTHETIC_TESTING_BOUNDARY:
    'OUTCOME_WORKING_DRAFT_OPENAI_RESPONSES_V30_SYNTHETIC_TESTING_BOUNDARY',
  OPENAI_RESPONSES_V31_ARL_ATTRIBUTION_BOUNDARIES:
    'OUTCOME_WORKING_DRAFT_OPENAI_RESPONSES_V31_ARL_ATTRIBUTION_BOUNDARIES',
  OPENAI_RESPONSES_V32_FRAMEWORK_METADATA_BOUNDARY:
    'OUTCOME_WORKING_DRAFT_OPENAI_RESPONSES_V32_FRAMEWORK_METADATA_BOUNDARY',
  OPENAI_RESPONSES_V33_CONSISTENT_CLAIM_INSTRUCTIONS:
    'OUTCOME_WORKING_DRAFT_OPENAI_RESPONSES_V33_CONSISTENT_CLAIM_INSTRUCTIONS',
  OPENAI_RESPONSES_V34_SHARED_RATIONALE_CONTRACT:
    'OUTCOME_WORKING_DRAFT_OPENAI_RESPONSES_V34_SHARED_RATIONALE_CONTRACT',
  OPENAI_RESPONSES_V35_EMPTY_QUALIFIED_DEPENDENCY_BOUNDARY:
    'OUTCOME_WORKING_DRAFT_OPENAI_RESPONSES_V35_EMPTY_QUALIFIED_DEPENDENCY_BOUNDARY',
  OPENAI_RESPONSES_V36_SOURCE_ATTRIBUTION_BOUNDARY:
    'OUTCOME_WORKING_DRAFT_OPENAI_RESPONSES_V36_SOURCE_ATTRIBUTION_BOUNDARY',
  OPENAI_RESPONSES_V37_MEANING_CLASS_AND_PROOF_DEFAULTS:
    'OUTCOME_WORKING_DRAFT_OPENAI_RESPONSES_V37_MEANING_CLASS_AND_PROOF_DEFAULTS',
  OPENAI_RESPONSES_V38_EXACT_BOUNDED_SUMMARY_WORDING:
    'OUTCOME_WORKING_DRAFT_OPENAI_RESPONSES_V38_EXACT_BOUNDED_SUMMARY_WORDING',
  OPENAI_RESPONSES_V39_CONDITIONAL_PROOF_SEQUENCE_BOUNDARIES:
    'OUTCOME_WORKING_DRAFT_OPENAI_RESPONSES_V39_CONDITIONAL_PROOF_SEQUENCE_BOUNDARIES',
  OPENAI_RESPONSES_V40_CLAIM_EVIDENCE_BOUNDARIES:
    'OUTCOME_WORKING_DRAFT_OPENAI_RESPONSES_V40_CLAIM_EVIDENCE_BOUNDARIES',
})

export const OUTCOME_WORKING_DRAFT_PROVIDER_CONFIG_VERSION =
  OUTCOME_WORKING_DRAFT_PROVIDER_CONFIG_VERSIONS.OPENAI_RESPONSES_V40_CLAIM_EVIDENCE_BOUNDARIES

export const OUTCOME_WORKING_DRAFT_MEANING_CONTRACT_VERSION =
  'ss-033-working-draft-meaning-boundary.v15'

export const OUTCOME_RENDERED_EXPRESSION_RL_PROVIDER_CONFIG_VERSION =
  'OUTCOME_RENDERED_EXPRESSION_RL_OPENAI_RESPONSES_V1'

export const OUTCOME_QUALITY_STAGE_PROVIDER_CONFIG_VERSIONS = Object.freeze({
  [OUTCOME_QUALITY_STAGES.FRAMEWORK_GUIDANCE]: Object.freeze(
    Object.values(OUTCOME_FRAMEWORK_GUIDANCE_PROVIDER_CONFIG_VERSIONS),
  ),
  [OUTCOME_QUALITY_STAGES.WORKING_DRAFT]: Object.freeze(
    Object.values(OUTCOME_WORKING_DRAFT_PROVIDER_CONFIG_VERSIONS),
  ),
  [OUTCOME_QUALITY_STAGES.ARL_MEANING_REVIEW]: Object.freeze([
    ...Object.values(OUTCOME_ARL_MEANING_REVIEW_PROVIDER_CONFIG_VERSIONS),
  ]),
  [OUTCOME_QUALITY_STAGES.OUTCOME_NARRATIVE_PLAN]: Object.freeze([]),
  [OUTCOME_QUALITY_STAGES.OUTPUT_SHAPING]: Object.freeze([]),
  [OUTCOME_QUALITY_STAGES.RENDERED_EXPRESSION_RL]: Object.freeze([
    OUTCOME_RENDERED_EXPRESSION_RL_PROVIDER_CONFIG_VERSION,
  ]),
})

export const OUTCOME_QUALITY_STAGE_ERROR_CODES = Object.freeze({
  INPUT_INVALID: 'OUTCOME_QUALITY_STAGE_INPUT_INVALID',
  KCP_INVALID: 'OUTCOME_QUALITY_STAGE_KCP_INVALID',
  KCP_NOT_ELIGIBLE: 'OUTCOME_QUALITY_STAGE_KCP_NOT_ELIGIBLE',
  STAGE_NOT_SUPPORTED: 'OUTCOME_QUALITY_STAGE_NOT_SUPPORTED',
  STAGE_BINDING_INVALID: 'OUTCOME_QUALITY_STAGE_BINDING_INVALID',
  FINGERPRINT_MISMATCH: 'OUTCOME_QUALITY_STAGE_FINGERPRINT_MISMATCH',
  VERSION_CONFLICT: 'OUTCOME_QUALITY_STAGE_VERSION_CONFLICT',
  PREDECESSOR_INVALID: 'OUTCOME_QUALITY_STAGE_PREDECESSOR_INVALID',
  RETRY_NOT_ALLOWED: 'OUTCOME_QUALITY_STAGE_RETRY_NOT_ALLOWED',
  TRANSACTION_REQUIRED: 'OUTCOME_QUALITY_STAGE_TRANSACTION_REQUIRED',
  AUDIT_FAILED: 'OUTCOME_QUALITY_STAGE_AUDIT_FAILED',
  PERSISTENCE_FAILED: 'OUTCOME_QUALITY_STAGE_PERSISTENCE_FAILED',
  IMMUTABLE: 'OUTCOME_QUALITY_STAGE_IMMUTABLE',
})

export const OUTCOME_KCP_ERROR_CODES = Object.freeze({
  INPUT_INVALID: 'OUTCOME_KCP_INPUT_INVALID',
  SOURCE_TRUTH_NOT_LOCKED: 'OUTCOME_KCP_SOURCE_TRUTH_NOT_LOCKED',
  SOURCE_TRUTH_INCOMPLETE: 'OUTCOME_KCP_SOURCE_TRUTH_INCOMPLETE',
  RUNTIME_STALE: 'OUTCOME_KCP_RUNTIME_STALE',
  RESOLUTION_BLOCKED: 'OUTCOME_KCP_RESOLUTION_BLOCKED',
  RESOLUTION_INTEGRITY_INVALID: 'OUTCOME_KCP_RESOLUTION_INTEGRITY_INVALID',
  FINGERPRINT_MISMATCH: 'OUTCOME_KCP_FINGERPRINT_MISMATCH',
  VERSION_CONFLICT: 'OUTCOME_KCP_VERSION_CONFLICT',
  IDENTICAL_RE_RESOLUTION: 'OUTCOME_KCP_IDENTICAL_RE_RESOLUTION',
  PREDECESSOR_INVALID: 'OUTCOME_KCP_PREDECESSOR_INVALID',
  TRANSACTION_REQUIRED: 'OUTCOME_KCP_TRANSACTION_REQUIRED',
  AUDIT_FAILED: 'OUTCOME_KCP_AUDIT_FAILED',
  PERSISTENCE_FAILED: 'OUTCOME_KCP_PERSISTENCE_FAILED',
  IMMUTABLE: 'OUTCOME_KCP_IMMUTABLE',
})
