export const LEGACY_VMF_SECTION_REASONING_CONTRACT_VERSION = 'ss-016-vmf-section-reasoning-v1'
export const VMF_SECTION_REASONING_CONTRACT_VERSION = 'ss-018-vmf-section-reasoning-v1'

export const VMF_SECTION_REASONING_CONTRACT_VERSIONS = Object.freeze([
  LEGACY_VMF_SECTION_REASONING_CONTRACT_VERSION,
  VMF_SECTION_REASONING_CONTRACT_VERSION,
])

