import {
  KNOWLEDGE_PACK_CATEGORIES,
} from './workspaceGovernance.js'

export const OUTCOME_STUDIO_CONTRACT_VERSION = 'outcome-studio.v1'

export const OUTCOME_STUDIO_PHASE = 'FOUNDATION_READINESS_ONLY'

export const OUTCOME_STUDIO_SESSION_STATUSES = Object.freeze({
  ACTIVE: 'ACTIVE',
  CLOSED: 'CLOSED',
  FAILED: 'FAILED',
})

export const OUTCOME_STUDIO_MESSAGE_ROLES = Object.freeze({
  ASSISTANT: 'ASSISTANT',
  USER: 'USER',
})

export const OUTCOME_STUDIO_MESSAGE_STATUSES = Object.freeze({
  GENERATED: 'GENERATED',
  SUBMITTED: 'SUBMITTED',
})

export const OUTCOME_STUDIO_RESPONSE_STATUSES = Object.freeze({
  PENDING_RESPONSE: 'PENDING_RESPONSE',
  RESPONSE_GENERATED: 'RESPONSE_GENERATED',
})

export const OUTCOME_STUDIO_DRAFT_STATUSES = Object.freeze({
  ACTIVE: 'ACTIVE',
  APPROVED: 'APPROVED',
  DISCARDED: 'DISCARDED',
  FAILED: 'FAILED',
})

export const OUTCOME_STUDIO_DRAFT_ITERATION_STATUSES = Object.freeze({
  CURRENT: 'CURRENT',
  SUPERSEDED: 'SUPERSEDED',
  REVERTED: 'REVERTED',
  APPROVED: 'APPROVED',
  FAILED: 'FAILED',
})

export const OUTCOME_STUDIO_DRAFT_ITERATION_TYPES = Object.freeze({
  INITIAL: 'INITIAL',
  REFINEMENT: 'REFINEMENT',
  REGENERATION: 'REGENERATION',
  REVERT: 'REVERT',
})

export const OUTCOME_STUDIO_REQUEST_INTENT_TYPES = Object.freeze({
  // The resolver currently emits the generative subset; remaining values reserve
  // stable contract vocabulary for defensive blockers and future resolver rules.
  NEW_OUTCOME_REQUEST: 'NEW_OUTCOME_REQUEST',
  REFINEMENT_REQUEST: 'REFINEMENT_REQUEST',
  CLARIFICATION_REQUEST: 'CLARIFICATION_REQUEST',
  CONTENT_EXPANSION: 'CONTENT_EXPANSION',
  CONTENT_REDUCTION: 'CONTENT_REDUCTION',
  TONE_STYLE_CHANGE: 'TONE_STYLE_CHANGE',
  AUDIENCE_CHANGE: 'AUDIENCE_CHANGE',
  STRUCTURAL_CHANGE: 'STRUCTURAL_CHANGE',
  EVIDENCE_CHALLENGE: 'EVIDENCE_CHALLENGE',
  REGENERATE_SECTION: 'REGENERATE_SECTION',
  APPROVE_FINALISE: 'APPROVE_FINALISE',
  PUBLISH_REQUEST: 'PUBLISH_REQUEST',
  AMBIGUOUS: 'AMBIGUOUS',
  UNSUPPORTED: 'UNSUPPORTED',
})

export const OUTCOME_STUDIO_REQUEST_RESOLUTION_STATUSES = Object.freeze({
  RESOLVED: 'RESOLVED',
  BLOCKED: 'BLOCKED',
})

export const OUTCOME_STUDIO_REQUEST_RESOLUTION_BLOCKER_CODES = Object.freeze({
  // Schema/style blockers remain defensive even though current built-in output
  // definitions always resolve both values after output-type resolution.
  PROMPT_MISSING: 'PROMPT_MISSING',
  UNSAFE_INTERNAL_REQUEST: 'UNSAFE_INTERNAL_REQUEST',
  OUTPUT_TYPE_UNRESOLVED: 'OUTPUT_TYPE_UNRESOLVED',
  OUTPUT_TYPE_AMBIGUOUS: 'OUTPUT_TYPE_AMBIGUOUS',
  OUTPUT_TYPE_UNSUPPORTED: 'OUTPUT_TYPE_UNSUPPORTED',
  OUTPUT_SCHEMA_UNRESOLVED: 'OUTPUT_SCHEMA_UNRESOLVED',
  STYLE_UNRESOLVED: 'STYLE_UNRESOLVED',
  DRAFT_REQUIRED: 'DRAFT_REQUIRED',
  REQUEST_INTENT_NOT_GENERATIVE: 'REQUEST_INTENT_NOT_GENERATIVE',
})

export const OUTCOME_STUDIO_EXPORT_FORMATS = Object.freeze({
  MARKDOWN: 'MARKDOWN',
  JSON: 'JSON',
  DOCX: 'DOCX',
  PDF: 'PDF',
})

export const OUTCOME_STUDIO_ASSET_STATUSES = Object.freeze({
  GENERATED: 'GENERATED',
  PUBLISHED: 'PUBLISHED',
  SUPERSEDED: 'SUPERSEDED',
  ARCHIVED: 'ARCHIVED',
})

export const OUTCOME_STUDIO_ASSET_VERSION_STATUSES = Object.freeze({
  CURRENT: 'CURRENT',
  SUPERSEDED: 'SUPERSEDED',
  ARCHIVED: 'ARCHIVED',
  FAILED: 'FAILED',
})

export const OUTCOME_STUDIO_SAFETY_GATE_STATUSES = Object.freeze({
  PASSED: 'PASSED',
  BLOCKED: 'BLOCKED',
})

export const OUTCOME_STUDIO_SAFETY_GATE_CODES = Object.freeze({
  SOURCE_OUTPUT_BOUND: 'SOURCE_OUTPUT_BOUND',
  TRUTH_SIGNATURE_BOUND: 'TRUTH_SIGNATURE_BOUND',
  KNOWLEDGE_PACKS_BOUND: 'KNOWLEDGE_PACKS_BOUND',
  PROMPT_PERSISTENCE_READY: 'PROMPT_PERSISTENCE_READY',
  RESPONSE_GENERATION_ENGINE: 'RESPONSE_GENERATION_ENGINE',
  ASSET_APPROVAL: 'ASSET_APPROVAL',
  ASSET_PUBLISH: 'ASSET_PUBLISH',
  EXPORT_RENDERER: 'EXPORT_RENDERER',
  TRUTH_UPDATE_WORKFLOW: 'TRUTH_UPDATE_WORKFLOW',
})

export const OUTCOME_STUDIO_READINESS_STATES = Object.freeze({
  READY: 'READY',
  READY_WITH_GAPS: 'READY_WITH_GAPS',
  BLOCKED: 'BLOCKED',
})

export const OUTCOME_STUDIO_BINDING_STATUSES = Object.freeze({
  PROJECTED: 'PROJECTED',
  BLOCKED: 'BLOCKED',
})

export const OUTCOME_STUDIO_BLOCKER_CODES = Object.freeze({
  SOURCE_OUTPUT_MISSING: 'SOURCE_OUTPUT_MISSING',
  KNOWLEDGE_PACK_BINDING_MISSING: 'KNOWLEDGE_PACK_BINDING_MISSING',
  ARL_PACK_MISSING: 'ARL_PACK_MISSING',
  RL_PACK_MISSING: 'RL_PACK_MISSING',
  OUTPUT_SCHEMA_PACK_MISSING: 'OUTPUT_SCHEMA_PACK_MISSING',
  TRUTH_CERTIFICATION_PACK_MISSING: 'TRUTH_CERTIFICATION_PACK_MISSING',
  OUTPUT_TYPE_PACK_MISSING: 'OUTPUT_TYPE_PACK_MISSING',
})

export const OUTCOME_STUDIO_REQUIRED_PACKS = Object.freeze([
  Object.freeze({
    packCategory: KNOWLEDGE_PACK_CATEGORIES.OUTCOME,
    packType: 'ARL',
    packKey: 'adaptive-reasoning-layer',
    label: 'Adaptive Reasoning Layer',
  }),
  Object.freeze({
    packCategory: KNOWLEDGE_PACK_CATEGORIES.OUTCOME,
    packType: 'RL',
    packKey: 'rendering-layer',
    label: 'Rendering Layer',
  }),
  Object.freeze({
    packCategory: KNOWLEDGE_PACK_CATEGORIES.OUTCOME,
    packType: 'OUTPUT_SCHEMA',
    packKey: 'output-schemas-pack',
    label: 'Output Schemas',
  }),
  Object.freeze({
    packCategory: KNOWLEDGE_PACK_CATEGORIES.PLATFORM,
    packType: 'TRUTH_CERTIFICATION',
    packKey: 'truth-certification-pack',
    label: 'Truth Certification',
  }),
  Object.freeze({
    packCategory: KNOWLEDGE_PACK_CATEGORIES.OUTCOME,
    packType: 'OUTPUT_TYPE_DEFINITION',
    packKey: 'outcome-output-types',
    label: 'Outcome Output Types',
  }),
])
