export const WORKSPACE_TYPES = Object.freeze({
  OUTCOME: 'OUTCOME',
  DISCOVERY: 'DISCOVERY',
  ADVISOR: 'ADVISOR',
  FRAMEWORK: 'FRAMEWORK',
})

export const WORKSPACE_ASSET_TYPES = Object.freeze({
  OUTCOME_NARRATIVE: 'OUTCOME_NARRATIVE',
  DISCOVERY_FINDING: 'DISCOVERY_FINDING',
  ADVISOR_RECOMMENDATION: 'ADVISOR_RECOMMENDATION',
  DECISION_MEMO: 'DECISION_MEMO',
})

export const WORKSPACE_MESSAGE_TYPES = Object.freeze({
  CUSTOMER_PROMPT: 'CUSTOMER_PROMPT',
  GOVERNED_RESPONSE: 'GOVERNED_RESPONSE',
  SYSTEM_EVENT: 'SYSTEM_EVENT',
})

export const RUNTIME_GRAPH_RELATIONSHIP_TYPES = Object.freeze({
  SESSION_BOUND_TO_TRUTH: 'SESSION_BOUND_TO_TRUTH',
  SESSION_BOUND_TO_PACK: 'SESSION_BOUND_TO_PACK',
  ASSET_DERIVED_FROM_TRUTH: 'ASSET_DERIVED_FROM_TRUTH',
  ASSET_DERIVED_FROM_SESSION: 'ASSET_DERIVED_FROM_SESSION',
  ASSET_PUBLISHED_FROM_VERSION: 'ASSET_PUBLISHED_FROM_VERSION',
})

export const RUNTIME_GRAPH_RELATIONSHIP_STATUSES = Object.freeze({
  ACTIVE: 'ACTIVE',
  SUPERSEDED: 'SUPERSEDED',
})

export const RUNTIME_GRAPH_NODE_TYPES = Object.freeze({
  RUNTIME_INSTANCE: 'RUNTIME_INSTANCE',
  WORKSPACE_SESSION: 'WORKSPACE_SESSION',
  WORKSPACE_MESSAGE: 'WORKSPACE_MESSAGE',
  WORKSPACE_ASSET: 'WORKSPACE_ASSET',
  WORKSPACE_ASSET_VERSION: 'WORKSPACE_ASSET_VERSION',
  TRUTH_SIGNATURE: 'TRUTH_SIGNATURE',
  KNOWLEDGE_PACK: 'KNOWLEDGE_PACK',
})

export const KNOWLEDGE_PACK_CATEGORIES = Object.freeze({
  OUTCOME: 'OUTCOME',
  DISCOVERY: 'DISCOVERY',
  ADVISOR: 'ADVISOR',
  FRAMEWORK: 'FRAMEWORK',
  PLATFORM: 'PLATFORM',
})

export const DEFAULT_OUTCOME_WORKSPACE_TYPE = WORKSPACE_TYPES.OUTCOME
export const DEFAULT_OUTCOME_ASSET_TYPE = WORKSPACE_ASSET_TYPES.OUTCOME_NARRATIVE
export const DEFAULT_OUTCOME_KNOWLEDGE_PACK_CATEGORY = KNOWLEDGE_PACK_CATEGORIES.OUTCOME

export const PLATFORM_KNOWLEDGE_PACK_TYPES = Object.freeze(new Set([
  'TRUTH_CERTIFICATION',
]))

export const resolveKnowledgePackCategory = ({ packCategory, packType } = {}) => {
  const normalizedCategory = String(packCategory || '').trim().toUpperCase()
  if (Object.values(KNOWLEDGE_PACK_CATEGORIES).includes(normalizedCategory)) {
    return normalizedCategory
  }

  const normalizedPackType = String(packType || '').trim().toUpperCase()
  if (PLATFORM_KNOWLEDGE_PACK_TYPES.has(normalizedPackType)) {
    return KNOWLEDGE_PACK_CATEGORIES.PLATFORM
  }

  return DEFAULT_OUTCOME_KNOWLEDGE_PACK_CATEGORY
}
