import { AUDIT_ACTIONS, RESOURCE_TYPES } from '../auditService.js'

export const GOVERNANCE_AUDIT_EVENT_CATEGORIES = Object.freeze({
  COMPONENT: 'COMPONENT',
  PACKAGE: 'PACKAGE',
  KNOWLEDGE_PACK: 'KNOWLEDGE_PACK',
  DEPENDENCY: 'DEPENDENCY',
  VALIDATION: 'VALIDATION',
  RUNTIME: 'RUNTIME',
})

export const GOVERNANCE_AUDIT_SEVERITIES = Object.freeze({
  INFO: 'INFO',
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
})

export const GOVERNANCE_AUDIT_EVENTS = Object.freeze({
  COMPONENT_CREATED: Object.freeze({
    eventKey: 'COMPONENT_CREATED',
    action: AUDIT_ACTIONS.COMPONENT_CREATED,
    category: GOVERNANCE_AUDIT_EVENT_CATEGORIES.COMPONENT,
    description: 'Runtime Control component created.',
    severity: GOVERNANCE_AUDIT_SEVERITIES.MEDIUM,
    requiresSnapshot: false,
    requiresChecksum: false,
    requiresDependencyGraph: false,
    isActive: true,
  }),
  COMPONENT_UPDATED: Object.freeze({
    eventKey: 'COMPONENT_UPDATED',
    action: AUDIT_ACTIONS.COMPONENT_UPDATED,
    category: GOVERNANCE_AUDIT_EVENT_CATEGORIES.COMPONENT,
    description: 'Runtime Control component updated.',
    severity: GOVERNANCE_AUDIT_SEVERITIES.MEDIUM,
    requiresSnapshot: false,
    requiresChecksum: false,
    requiresDependencyGraph: false,
    isActive: true,
  }),
  COMPONENT_CLONED: Object.freeze({
    eventKey: 'COMPONENT_CLONED',
    action: AUDIT_ACTIONS.COMPONENT_CLONED,
    category: GOVERNANCE_AUDIT_EVENT_CATEGORIES.COMPONENT,
    description: 'Runtime Control component cloned.',
    severity: GOVERNANCE_AUDIT_SEVERITIES.MEDIUM,
    requiresSnapshot: false,
    requiresChecksum: false,
    requiresDependencyGraph: false,
    isActive: true,
  }),
  COMPONENT_DEPRECATED: Object.freeze({
    eventKey: 'COMPONENT_DEPRECATED',
    action: AUDIT_ACTIONS.COMPONENT_DEPRECATED,
    category: GOVERNANCE_AUDIT_EVENT_CATEGORIES.COMPONENT,
    description: 'Runtime Control component deprecated.',
    severity: GOVERNANCE_AUDIT_SEVERITIES.HIGH,
    requiresSnapshot: false,
    requiresChecksum: false,
    requiresDependencyGraph: false,
    isActive: true,
  }),
  COMPONENT_LOCKED: Object.freeze({
    eventKey: 'COMPONENT_LOCKED',
    action: AUDIT_ACTIONS.COMPONENT_LOCKED,
    category: GOVERNANCE_AUDIT_EVENT_CATEGORIES.COMPONENT,
    description: 'Runtime Control component locked by governed package evidence.',
    severity: GOVERNANCE_AUDIT_SEVERITIES.HIGH,
    requiresSnapshot: false,
    requiresChecksum: false,
    requiresDependencyGraph: false,
    isActive: true,
  }),
  PACKAGE_CREATED: Object.freeze({
    eventKey: 'PACKAGE_CREATED',
    action: AUDIT_ACTIONS.FRAMEWORK_PACKAGE_CREATED,
    resourceType: RESOURCE_TYPES.FrameworkPackage,
    category: GOVERNANCE_AUDIT_EVENT_CATEGORIES.PACKAGE,
    description: 'Framework package created.',
    severity: GOVERNANCE_AUDIT_SEVERITIES.MEDIUM,
    requiresSnapshot: false,
    requiresChecksum: false,
    requiresDependencyGraph: false,
    isActive: true,
  }),
  PACKAGE_CLONED: Object.freeze({
    eventKey: 'PACKAGE_CLONED',
    action: AUDIT_ACTIONS.FRAMEWORK_PACKAGE_CLONED,
    resourceType: RESOURCE_TYPES.FrameworkPackage,
    category: GOVERNANCE_AUDIT_EVENT_CATEGORIES.PACKAGE,
    description: 'Framework package cloned.',
    severity: GOVERNANCE_AUDIT_SEVERITIES.HIGH,
    requiresSnapshot: false,
    requiresChecksum: false,
    requiresDependencyGraph: false,
    isActive: true,
  }),
  PACKAGE_VALIDATED: Object.freeze({
    eventKey: 'PACKAGE_VALIDATED',
    action: AUDIT_ACTIONS.FRAMEWORK_PACKAGE_VALIDATED,
    resourceType: RESOURCE_TYPES.FrameworkPackage,
    category: GOVERNANCE_AUDIT_EVENT_CATEGORIES.PACKAGE,
    description: 'Framework package validated with locked dependency evidence.',
    severity: GOVERNANCE_AUDIT_SEVERITIES.HIGH,
    requiresSnapshot: true,
    requiresChecksum: true,
    requiresDependencyGraph: true,
    isActive: true,
  }),
  PACKAGE_ACTIVATED: Object.freeze({
    eventKey: 'PACKAGE_ACTIVATED',
    action: AUDIT_ACTIONS.FRAMEWORK_PACKAGE_ACTIVATED,
    resourceType: RESOURCE_TYPES.FrameworkPackage,
    category: GOVERNANCE_AUDIT_EVENT_CATEGORIES.PACKAGE,
    description: 'Framework package activated for runtime deployment.',
    severity: GOVERNANCE_AUDIT_SEVERITIES.CRITICAL,
    requiresSnapshot: true,
    requiresChecksum: true,
    requiresDependencyGraph: true,
    isActive: true,
  }),
  RUNTIME_ACTIVATION_COMPLETED: Object.freeze({
    eventKey: 'RUNTIME_ACTIVATION_COMPLETED',
    action: AUDIT_ACTIONS.RUNTIME_ACTIVATION_COMPLETED,
    resourceType: RESOURCE_TYPES.FrameworkPackage,
    category: GOVERNANCE_AUDIT_EVENT_CATEGORIES.RUNTIME,
    description: 'Runtime activation completed and immutable snapshot registered.',
    severity: GOVERNANCE_AUDIT_SEVERITIES.CRITICAL,
    requiresSnapshot: true,
    requiresChecksum: true,
    requiresDependencyGraph: true,
    isActive: true,
  }),
  RUNTIME_DEPLOYMENT_REGISTERED: Object.freeze({
    eventKey: 'RUNTIME_DEPLOYMENT_REGISTERED',
    action: AUDIT_ACTIONS.RUNTIME_DEPLOYMENT_REGISTERED,
    resourceType: RESOURCE_TYPES.FrameworkPackage,
    category: GOVERNANCE_AUDIT_EVENT_CATEGORIES.RUNTIME,
    description: 'Runtime deployment registered for active package execution.',
    severity: GOVERNANCE_AUDIT_SEVERITIES.HIGH,
    requiresSnapshot: true,
    requiresChecksum: true,
    requiresDependencyGraph: true,
    isActive: true,
  }),
  PACKAGE_DEPRECATED: Object.freeze({
    eventKey: 'PACKAGE_DEPRECATED',
    action: AUDIT_ACTIONS.PACKAGE_DEPRECATED,
    resourceType: RESOURCE_TYPES.FrameworkPackage,
    category: GOVERNANCE_AUDIT_EVENT_CATEGORIES.PACKAGE,
    description: 'Framework package deprecated.',
    severity: GOVERNANCE_AUDIT_SEVERITIES.HIGH,
    requiresSnapshot: false,
    requiresChecksum: false,
    requiresDependencyGraph: false,
    isActive: true,
  }),
  DEPENDENCY_LINKED: Object.freeze({
    eventKey: 'DEPENDENCY_LINKED',
    action: AUDIT_ACTIONS.DEPENDENCY_LINKED,
    resourceType: RESOURCE_TYPES.FrameworkPackage,
    category: GOVERNANCE_AUDIT_EVENT_CATEGORIES.DEPENDENCY,
    description: 'Runtime Control dependency linked.',
    severity: GOVERNANCE_AUDIT_SEVERITIES.MEDIUM,
    requiresSnapshot: false,
    requiresChecksum: false,
    requiresDependencyGraph: false,
    isActive: true,
  }),
  DEPENDENCY_UPDATED: Object.freeze({
    eventKey: 'DEPENDENCY_UPDATED',
    action: AUDIT_ACTIONS.DEPENDENCY_UPDATED,
    resourceType: RESOURCE_TYPES.FrameworkPackage,
    category: GOVERNANCE_AUDIT_EVENT_CATEGORIES.DEPENDENCY,
    description: 'Runtime Control dependency updated.',
    severity: GOVERNANCE_AUDIT_SEVERITIES.MEDIUM,
    requiresSnapshot: false,
    requiresChecksum: false,
    requiresDependencyGraph: false,
    isActive: true,
  }),
  DEPENDENCY_IMPACT_ANALYSIS: Object.freeze({
    eventKey: 'DEPENDENCY_IMPACT_ANALYSIS',
    action: AUDIT_ACTIONS.DEPENDENCY_IMPACT_ANALYSIS,
    resourceType: RESOURCE_TYPES.FrameworkPackage,
    category: GOVERNANCE_AUDIT_EVENT_CATEGORIES.DEPENDENCY,
    description: 'Runtime Control dependency impact analysis evaluated.',
    severity: GOVERNANCE_AUDIT_SEVERITIES.MEDIUM,
    requiresSnapshot: false,
    requiresChecksum: false,
    requiresDependencyGraph: true,
    isActive: true,
  }),
  VALIDATION_STARTED: Object.freeze({
    eventKey: 'VALIDATION_STARTED',
    action: AUDIT_ACTIONS.VALIDATION_STARTED,
    resourceType: RESOURCE_TYPES.FrameworkPackage,
    category: GOVERNANCE_AUDIT_EVENT_CATEGORIES.VALIDATION,
    description: 'Governed package validation started.',
    severity: GOVERNANCE_AUDIT_SEVERITIES.INFO,
    requiresSnapshot: false,
    requiresChecksum: false,
    requiresDependencyGraph: false,
    isActive: true,
  }),
  VALIDATION_PASSED: Object.freeze({
    eventKey: 'VALIDATION_PASSED',
    action: AUDIT_ACTIONS.VALIDATION_PASSED,
    resourceType: RESOURCE_TYPES.FrameworkPackage,
    category: GOVERNANCE_AUDIT_EVENT_CATEGORIES.VALIDATION,
    description: 'Governed package validation passed.',
    severity: GOVERNANCE_AUDIT_SEVERITIES.HIGH,
    requiresSnapshot: true,
    requiresChecksum: true,
    requiresDependencyGraph: true,
    isActive: true,
  }),
  VALIDATION_FAILED: Object.freeze({
    eventKey: 'VALIDATION_FAILED',
    action: AUDIT_ACTIONS.VALIDATION_FAILED,
    resourceType: RESOURCE_TYPES.FrameworkPackage,
    category: GOVERNANCE_AUDIT_EVENT_CATEGORIES.VALIDATION,
    description: 'Governed package validation failed.',
    severity: GOVERNANCE_AUDIT_SEVERITIES.HIGH,
    requiresSnapshot: true,
    requiresChecksum: true,
    requiresDependencyGraph: false,
    isActive: true,
  }),
  CHECKPOINT_PASSED: Object.freeze({
    eventKey: 'CHECKPOINT_PASSED',
    action: AUDIT_ACTIONS.CHECKPOINT_PASSED,
    resourceType: RESOURCE_TYPES.FrameworkPackage,
    category: GOVERNANCE_AUDIT_EVENT_CATEGORIES.VALIDATION,
    description: 'Runtime architecture checkpoint passed.',
    severity: GOVERNANCE_AUDIT_SEVERITIES.HIGH,
    requiresSnapshot: true,
    requiresChecksum: true,
    requiresDependencyGraph: true,
    isActive: true,
  }),
  CHECKPOINT_FAILED: Object.freeze({
    eventKey: 'CHECKPOINT_FAILED',
    action: AUDIT_ACTIONS.CHECKPOINT_FAILED,
    resourceType: RESOURCE_TYPES.FrameworkPackage,
    category: GOVERNANCE_AUDIT_EVENT_CATEGORIES.VALIDATION,
    description: 'Runtime architecture checkpoint failed.',
    severity: GOVERNANCE_AUDIT_SEVERITIES.HIGH,
    requiresSnapshot: true,
    requiresChecksum: true,
    requiresDependencyGraph: false,
    isActive: true,
  }),
  RUNTIME_VALIDATION_ALLOWED: Object.freeze({
    eventKey: 'RUNTIME_VALIDATION_ALLOWED',
    action: AUDIT_ACTIONS.RUNTIME_VALIDATION_ALLOWED,
    resourceType: RESOURCE_TYPES.FrameworkPackage,
    category: GOVERNANCE_AUDIT_EVENT_CATEGORIES.VALIDATION,
    description: 'Package-level Runtime Validation allowed activation readiness.',
    severity: GOVERNANCE_AUDIT_SEVERITIES.HIGH,
    requiresSnapshot: true,
    requiresChecksum: true,
    requiresDependencyGraph: false,
    isActive: true,
  }),
  RUNTIME_VALIDATION_BLOCKED: Object.freeze({
    eventKey: 'RUNTIME_VALIDATION_BLOCKED',
    action: AUDIT_ACTIONS.RUNTIME_VALIDATION_BLOCKED,
    resourceType: RESOURCE_TYPES.FrameworkPackage,
    category: GOVERNANCE_AUDIT_EVENT_CATEGORIES.VALIDATION,
    description: 'Package-level Runtime Validation blocked activation readiness.',
    severity: GOVERNANCE_AUDIT_SEVERITIES.HIGH,
    requiresSnapshot: true,
    requiresChecksum: true,
    requiresDependencyGraph: false,
    isActive: true,
  }),
  FRAMEWORK_EXECUTED: Object.freeze({
    eventKey: 'FRAMEWORK_EXECUTED',
    action: AUDIT_ACTIONS.FRAMEWORK_EXECUTED,
    resourceType: RESOURCE_TYPES.FrameworkPackage,
    category: GOVERNANCE_AUDIT_EVENT_CATEGORIES.RUNTIME,
    description: 'Framework package executed at runtime.',
    severity: GOVERNANCE_AUDIT_SEVERITIES.HIGH,
    requiresSnapshot: false,
    requiresChecksum: true,
    requiresDependencyGraph: false,
    isActive: true,
  }),
  POLICY_EVALUATED: Object.freeze({
    eventKey: 'POLICY_EVALUATED',
    action: AUDIT_ACTIONS.POLICY_EVALUATED,
    resourceType: RESOURCE_TYPES.WorkflowPolicy,
    category: GOVERNANCE_AUDIT_EVENT_CATEGORIES.RUNTIME,
    description: 'Workflow policy evaluated at runtime.',
    severity: GOVERNANCE_AUDIT_SEVERITIES.MEDIUM,
    requiresSnapshot: false,
    requiresChecksum: false,
    requiresDependencyGraph: false,
    isActive: true,
  }),
  AGENT_EXECUTED: Object.freeze({
    eventKey: 'AGENT_EXECUTED',
    action: AUDIT_ACTIONS.AGENT_EXECUTED,
    resourceType: RESOURCE_TYPES.RuntimeAgent,
    category: GOVERNANCE_AUDIT_EVENT_CATEGORIES.RUNTIME,
    description: 'Runtime agent executed.',
    severity: GOVERNANCE_AUDIT_SEVERITIES.MEDIUM,
    requiresSnapshot: false,
    requiresChecksum: false,
    requiresDependencyGraph: false,
    isActive: true,
  }),
  KNOWLEDGE_PACK_GOVERNANCE_MAPPING_APPLIED: Object.freeze({
    eventKey: 'KNOWLEDGE_PACK_GOVERNANCE_MAPPING_APPLIED',
    action: AUDIT_ACTIONS.KNOWLEDGE_PACK_GOVERNANCE_MAPPING_APPLIED,
    resourceType: RESOURCE_TYPES.KnowledgePack,
    category: GOVERNANCE_AUDIT_EVENT_CATEGORIES.KNOWLEDGE_PACK,
    description: 'Governed Knowledge Pack metadata mapping applied.',
    severity: GOVERNANCE_AUDIT_SEVERITIES.HIGH,
    requiresSnapshot: true,
    requiresChecksum: true,
    requiresDependencyGraph: false,
    isActive: true,
  }),
})

export const getGovernanceAuditEvent = (eventKey) =>
  GOVERNANCE_AUDIT_EVENTS[String(eventKey || '').trim().toUpperCase()] || null

export default GOVERNANCE_AUDIT_EVENTS
